### ISSUE TITLE
Playlist doesn't load

### ISSUE THREAD

**Issue by yashiscool123** [4gray/iptvnator#104]
I'm trying to add the following playlist but it just doesn't work in the iptvnator app while it still works in all other apps like VLC etc.

https://snehtv.tk/snehiptv.m3u8

Also, there's no process to stop the loading of a playlist

**Comment by what-a** [comment]
Testing in Linux; I could not get that URL to load in VLC nor IPTVnator. It did load in mpv and Hypnotix (which is based upon mpv).

**Comment by Axel-Erfurt** [comment]
I also cannot load it in iptvnator on Linux Mint via URL.
After downloading the playlist I can load it in iptvnator.

**Comment by phartshorn** [comment]
Looking at the response headers for the above url, it appears to be a cross origin (CORS) restriction:

```
$ wget -q -S "https://snehtv.tk/snehiptv.m3u8" -O /dev/null
  HTTP/1.1 302 Found
  x-ratelimit-limit: 50
  x-ratelimit-remaining: 49
  x-ratelimit-reset: 49
  connection: close
  content-type: text/html; charset=utf-8
  x-powered-by: Short.io link shortener
  cache-control: no-cache, no-store, max-age=0, must-revalidate
  pragma: no-cache
  location: https://techiesneh.in1.bitmana.io/snehapi/snehiptv.m3u8
  content-length: 0
  Date: Thu, 06 Jan 2022 00:08:09 GMT
  HTTP/1.1 200 OK
  Server: openresty
  Date: Thu, 06 Jan 2022 00:08:12 GMT
  Content-Type: application/vnd.apple.mpegurl
  Content-Length: 427361
  Connection: keep-alive
  Content-Security-Policy: frame-ancestors 'self';frame-src 'self';
  Cross-Origin-Embedder-Policy: unsafe-none
  Cross-Origin-Opener-Policy: same-origin-allow-popups
  Cross-Origin-Resource-Policy: same-origin
  Permissions-Policy: geolocation=(self), payment=(self)
  Referrer-Policy: strict-origin-when-cross-origin
  X-Content-Type-Options: nosniff
  X-Frame-Options: SAMEORIGIN
  X-Permitted-Cross-Domain-Policies: none
  X-XSS-Protection: 1; mode=block;
  Last-Modified: Sat, 01 Jan 2022 18:08:04 GMT
  ETag: "68561-5d4892b342900"
  Accept-Ranges: bytes
  X-Resolver-IP: 103.217.220.8
  Strict-Transport-Security: max-age=15811200
```

As electron apps run in a browser, they're bound by the browsers restrictions.

I performed a quick test using:

```
<html>
  <head>
        <script>
          let r = new XMLHttpRequest();
          r.open('get', 'https://snehtv.tk/snehiptv.m3u8', false);
          r.send();
        </script>
  </head>
</html>
```

When loaded (from a web server) the above request resulted in a CORS error (as can be observed in the network tab)

**Comment by 4gray** [comment]
Thanks for the report and investigation guys. 
CORS shouldn't be a problem, since the request to load the playlist is called from the electron main process, i.e. not from the client, but from the node.js world. 

According to the logs, the problem is in the https certificate of the domain. 

```
(node:58348) UnhandledPromiseRejectionWarning: Error: certificate has expired
    at TLSSocket.onConnectSecure (_tls_wrap.js:1501:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:936:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:710:12)
```

But in any case the error handling should be improved (display user-friendly error message and get rid of endless loading spinner).
