### ISSUE TITLE
Tab names do not retain their white font highlight.

### ISSUE THREAD

**Issue by what-a** [4gray/iptvnator#108]
Clicking on a tab name, highlights the tab that you are using. For example, if you click on "ALL CHANNELS" it is highlighted in white font:
![image](https://user-images.githubusercontent.com/88639906/148317920-9d0bc7d6-ff8f-46e6-9daa-6a1d4f44eb99.png)

However, once you click on something within that tab, the highlight for the tab name disappears. For example, once you click on a channel, the "ALL CHANNELS" name is no longer highlighted in white. This can be confusing (especially for new users) since they can't tell which of the three tabs they are currently viewing.
![image](https://user-images.githubusercontent.com/88639906/148318093-4905fc12-b511-41c6-9bec-57743d54c954.png)
The above example is when using dark theme. The same issue occurs (except with opposite colors) when using light theme.
This issue occurs on Windows 10, Linux and macOS.

**Comment by 4gray** [comment]
Changed now, thanks!
