### ISSUE TITLE
EPG does not display despite "tvg-id" matching in playlist.m3u and epg.xml

### ISSUE THREAD

**Issue by what-a** [4gray/iptvnator#114]
A great source of free EPGs is:  https://github.com/iptv-org/epg
However, I'm unable to get any of their EPGs to work within IPTVnator (though I do get them to work in other IPTV players such as Astronica).  Has anyone had success with any EPG from IPTV-org in IPTVnator?

**Comment by Axel-Erfurt** [comment]
I use https://iptv-org.github.io/epg/guides/de/hd-plus.de.epg.xml from there and it works fine.

**Comment by what-a** [comment]
@Axel-Erfurt Thanks for the feedback. I'm doing more testing in hopes of figuring out the root cause of the issue that I'm experiencing.

**Comment by Axel-Erfurt** [comment]
The channel names:

```1-2-3 TV
13th Street Deutschland
3sat
ARD Alpha
ARTE Deutsch
ATV
ATV 2
AXN Deutschland
Anixe HD Serie
AstroTV
Augsburg TV
Bayerisches Fernsehen Nord
Bibel TV
Bloomberg TV Europe
Boomerang Deutschland
Cartoon Network Deutschland
Channel 21
Comedy Central Deutschland
DMAX Deutschland
Das Erste
Deluxe Music
Deutsches Musik Fernsehen
Die Neue Zeit TV
Discovery Channel Deutschland
Disney Channel Deutschland
E! Europe
EWTN auf Deutsch
EuroNews Deutsch
Eurosport 1 Germany
Franken Fernsehen
GoTV
HR Fernsehen
HSE
HSE Extra
Heimatkanal
History Deutschland
Hope TV Deutsch
JML Direct
Junior
Juwelo
KIKA
K-TV
Kabel Eins Classics
Kabel Eins Deutschland
Kinowelt TV
L TV
MTV Germany
MTV Hits Europe
MTV Live HD
MTV Music 24
Motorvision TV
München TV
NPO 1
NPO 2
N-TV
National Geographic Deutschland
National Geographic Wild Deutschland
Nitro Deutschland
ORF 1
ORF 2
ORF III
ORF Sport +
One
Pearl TV
Phoenix
ProSieben Deutschland
ProSieben Maxx Deutschland
Puls 4
QVC Deutschland
QVC Zwei
RFO
RTL Crime Deutschland
RTL Deutschland
RTL Living Deutschland
RTL Zwei Deutschland
Regio TV Satellit
RheinMain TV
RiC
Romance TV Deutschland
SRF 1
SRF Zwei
SR Fernsehen
Sat. 1 Deutschland
Sat. 1 Emotions
Sat. 1 Gold Deutschland
Servus TV Deutschland
Sixx Deutschland
Sky Atlantic
Sky Cinema Action
Sky Cinema Hits
Sky Cinema Nostalgie
Sky Comedy
Sky Krimi
Sky Sport 1
Sky Sport 2
Sky Sport Austria 1
Sky Sport Bundesliga 1
Sky Sport Bundesliga 2
Sky Sport Bundesliga 3
Sky Sport Bundesliga 4
Sky Sport News
Sonnenklar TV
Sport 1
Sport 1+
Sportdigital Fussball
Stingray Classica
Super RTL Deutschland
Syfy Deutschland
TLC Germany
TNT Film
TNT Serie
TVA Ostbayern
TV Oberfranken
Tagesschau 24
Tele 5
Universal TV Deutschland
Vox Deutschland
Welt
Welt der Wunder TV
ZDF
ZDF Info
ZDF Neo
```

**Comment by Axel-Erfurt** [comment]
This is how I get the names with python3

```python
import xml.etree.ElementTree as ET
import requests

id_list = []
name_list = []
epg_url = "https://iptv-org.github.io/epg/guides/de/hd-plus.de.epg.xml"
epg = requests.get(epg_url)

root = ET.fromstring(epg.content)

for b in root.findall('channel'):
    id_list.append(b.get("id"))
    name_list.append(b.find("display-name").text)

print('\n'.join(name_list))
```

**Comment by what-a** [comment]
I've identified the problem.

IPTVnator will display EPG info when there's a "display name" match (between playlist and epg files).
IPTVnator will not display EPG info when there's a "display name" mismatch (between playlist and epg files). 
Request: update IPTVnator so that a "tvg-id" match (between playlist and epg files) always results in the display of EPG info regardless of "display name" mismatch.

Below examples demonstrate how IPTVnator currently works (green is successful EPG display, and red is failed EPG display).

![image](https://user-images.githubusercontent.com/88639906/154866952-462ccca8-b561-411d-8dd3-ecc20dbc86eb.png)

**Comment by what-a** [comment]
In other words, a matching "tvg-id" should be the primary link from playlist.m3u to epg.xml.
A link based upon matching "display name" should only be attempted if a match using tvg-id failed.

**Comment by Axel-Erfurt** [comment]
That will never work in the end.
Each EPG uses different "display name".
Not every playlist has "tvg-id"

For example, I looked at 3 different german EPGs, the values in "display-name" are never identical.
one uses "ZDF neo", the other "ZDFneo" or "ZDF_neo"

**Comment by what-a** [comment]
> That will never work in the end. Each EPG uses different "display name". Not every playlist has "tvg-id"
> 
> For example, I looked at 3 different german EPGs, the values in "display-name" are never identical. one uses "ZDF neo", the other "ZDFneo" or "ZDF_neo"

We are saying the same thing. Today, EPG in IPTVnator will only work based upon matching "display name."  That is problematic. The primary match needs to be based upon matching "tvg-id."

**Comment by alynow** [comment]
> The channel names:
> 
> ```1-2-3 TV
> 13th Street Deutschland
> 3sat
> ARD Alpha
> ARTE Deutsch
> ATV
> ATV 2
> AXN Deutschland
> Anixe HD Serie
> AstroTV
> Augsburg TV
> Bayerisches Fernsehen Nord
> Bibel TV
> Bloomberg TV Europe
> Boomerang Deutschland
> Cartoon Network Deutschland
> Channel 21
> Comedy Central Deutschland
> DMAX Deutschland
> Das Erste
> Deluxe Music
> Deutsches Musik Fernsehen
> Die Neue Zeit TV
> Discovery Channel Deutschland
> Disney Channel Deutschland
> E! Europe
> EWTN auf Deutsch
> EuroNews Deutsch
> Eurosport 1 Germany
> Franken Fernsehen
> GoTV
> HR Fernsehen
> HSE
> HSE Extra
> Heimatkanal
> History Deutschland
> Hope TV Deutsch
> JML Direct
> Junior
> Juwelo
> KIKA
> K-TV
> Kabel Eins Classics
> Kabel Eins Deutschland
> Kinowelt TV
> L TV
> MTV Germany
> MTV Hits Europe
> MTV Live HD
> MTV Music 24
> Motorvision TV
> München TV
> NPO 1
> NPO 2
> N-TV
> National Geographic Deutschland
> National Geographic Wild Deutschland
> Nitro Deutschland
> ORF 1
> ORF 2
> ORF III
> ORF Sport +
> One
> Pearl TV
> Phoenix
> ProSieben Deutschland
> ProSieben Maxx Deutschland
> Puls 4
> QVC Deutschland
> QVC Zwei
> RFO
> RTL Crime Deutschland
> RTL Deutschland
> RTL Living Deutschland
> RTL Zwei Deutschland
> Regio TV Satellit
> RheinMain TV
> RiC
> Romance TV Deutschland
> SRF 1
> SRF Zwei
> SR Fernsehen
> Sat. 1 Deutschland
> Sat. 1 Emotions
> Sat. 1 Gold Deutschland
> Servus TV Deutschland
> Sixx Deutschland
> Sky Atlantic
> Sky Cinema Action
> Sky Cinema Hits
> Sky Cinema Nostalgie
> Sky Comedy
> Sky Krimi
> Sky Sport 1
> Sky Sport 2
> Sky Sport Austria 1
> Sky Sport Bundesliga 1
> Sky Sport Bundesliga 2
> Sky Sport Bundesliga 3
> Sky Sport Bundesliga 4
> Sky Sport News
> Sonnenklar TV
> Sport 1
> Sport 1+
> Sportdigital Fussball
> Stingray Classica
> Super RTL Deutschland
> Syfy Deutschland
> TLC Germany
> TNT Film
> TNT Serie
> TVA Ostbayern
> TV Oberfranken
> Tagesschau 24
> Tele 5
> Universal TV Deutschland
> Vox Deutschland
> Welt
> Welt der Wunder TV
> ZDF
> ZDF Info
> ZDF Neo
> ```

Könnte ich diese m3u list haben bitte?

**Comment by Axel-Erfurt** [comment]
It's not a m3u list, it's epg

https://iptv-org.github.io/epg/guides/de/hd-plus.de.epg.xml

**Comment by 4gray** [comment]
> In other words, a matching "tvg-id" should be the primary link from playlist.m3u to epg.xml.
A link based upon matching "display name" should only be attempted if a match using tvg-id failed.

This is how it works in the new version (v0.10.0).
