### ISSUE TITLE
Load https playlist

### ISSUE THREAD

**Issue by linuxubuntu63** [4gray/iptvnator#116]
Hi.
Many thanks for your project.
But i can add a https playlist, it search for adding but nothing come.
Thanks for help

**Comment by 4gray** [comment]
Hi @linuxubuntu63, thanks for the feedback! It's hard to understand the issue without an example, possible problem could be an expired https certificate on the domain where the playlist is hosted, something similar we had here - https://github.com/4gray/iptvnator/issues/104

**Comment by JamonesAlVapor** [comment]
I am able to reproduce this. There's something preventing URLs that are running any Lets Encrypt SSL certificates from working, at least on the Linux AppImage.

```
(node:1763917) UnhandledPromiseRejectionWarning: Error: certificate has expired
    at TLSSocket.onConnectSecure (_tls_wrap.js:1484:34)
    at TLSSocket.emit (events.js:310:20)
    at TLSSocket._finishInit (_tls_wrap.js:927:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:697:12)
(node:1763917) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
```

You can reproduce this by trying, for example, to load https://letsencrypt.org as a playlist, even though it's obviously not an m3u playlist it fails with this error before even trying to parse it.

I suspect the AppImage may be bundling an outdated TLS cert chain or something along those lines given the recent [letsencrypt certificate changes](https://letsencrypt.org/2019/04/15/transitioning-to-isrg-root.html)
