### ISSUE TITLE
Capitalize the app name

### ISSUE THREAD

**Issue by xmha97** [4gray/iptvnator#117]
Please capitalize the app name.
![image](https://user-images.githubusercontent.com/23485114/151471235-c01b4fd6-7964-43fd-807e-bab4e26ee242.png)
`iptvnator` -> `IPTVnator`

**Comment by 4gray** [comment]
Closed with https://github.com/4gray/iptvnator/commit/36d3eaa54d546de64a9522583772cf411a2866c4
