### ISSUE TITLE
AppImage Core Dumped - FATAL:gpu_data_manager_impl_private.cc

### ISSUE THREAD

**Issue by dimisc** [4gray/iptvnator#124]
When trying to load the IPTVNATOR appimage it fails with:

[5562:0215/181054.541837:FATAL:gpu_data_manager_impl_private.cc(442)] GPU process isn't usable. Goodbye.
[1]    5562 trace trap (core dumped)  ./iptvnator-0.9.0.AppImage

I am using an NVidia GTX 980 with proprietary drivers (version: 510.47.03).

I am on Arch (Kernel: 5.16.9-arch1-1) on a Ryzen 3600 CPU.

The problem persists after reboot and after cleaning the .config/iptvnator folder and running the appimage again.

**Comment by 4gray** [comment]
In the new version (v0.10.0) the base dependencies have been updated including electron, hopefully this will solve the problem.
