### ISSUE TITLE
For Android ?

### ISSUE THREAD

**Issue by spotanjo3** [4gray/iptvnator#129]
I loved your app for macOS. I enjoyed it a lot and I wonder if you can do this for Android ? I would like to have it on my Android TV Sony Bravia OLED because I tried other iptv androids and I don't liked them. I prefer your app. Please reconsider ? Thanks.

**Comment by 4gray** [comment]
Hi, thank you for the feedback :+1:  There is no separate application for Android, but you can try the PWA: https://iptvnator.vercel.app/
