### ISSUE TITLE
HLS stream not playing in IPTVnator

### ISSUE THREAD

**Issue by what-a** [4gray/iptvnator#134]
Not sure if this is a bug or not...
This stream plays fine within an HLS browser extension as well as in VLC, but not in IPTVnator. 
Give it a try...

http://162.250.220.76/CNN/tracks-v1a1/mono.m3u8

![image](https://user-images.githubusercontent.com/88639906/163659037-31edd15b-88b8-4411-b309-9156821ee78b.png)

Any idea why IPTVnator is not able to play it?

**Comment by 4gray** [comment]
That's interesting, can you please tell me which browser extension plays the playlist? Just to compare the player dependencies.

**Comment by what-a** [comment]
Version 4.0.0 within Firefox...
![image](https://user-images.githubusercontent.com/88639906/163878996-ff607192-848b-4ad0-a008-9a5b20e341c1.png)

**Comment by 4gray** [comment]
Thanks! It works fine in firefox, but I haven't found any extensions that work in Chrome (because of electron) :thinking: (https://chrome.google.com/webstore/detail/native-mpeg-dash-%20-hls-pl/cjfbmleiaobegagekpmlhmaadepdeedn from the same developer but for Chrome, doesn't work)

**Comment by what-a** [comment]
Similar issue with .mpd streams. Play fine in the browser but not in IPTVnator. For example:
https://edge1.1internet.tv/dash-live2/streams/1tv-dvr/1tvdash.mpd

**Comment by what-a** [comment]
😢
http://162.250.220.76:80/E!/tracks-v1a1/mono.m3u8
http://162.250.220.76:80/MTV/tracks-v1a1/mono.m3u8
http://162.250.220.76:80/TSN-1/tracks-v1a1/mono.m3u8
http://162.250.220.76:80/TSN-2/tracks-v1a1/mono.m3u8
http://162.250.220.76:80/TSN-3/tracks-v1a1/mono.m3u8
http://162.250.220.76:80/TSN-4/tracks-v1a1/mono.m3u8
http://162.250.220.76:80/TSN-5/tracks-v1a1/mono.m3u8
http://200.123.211.41:80/TNT/tracks-v1a1/mono.m3u8
http://200.123.211.41:80/USAHD/tracks-v1a1/mono.m3u8
http://213.7.193.54:4000/play/bbc1/index.m3u8

**Comment by 4gray** [comment]
I hope the integration of mpv and vlc player has solved these issues
