### ISSUE TITLE
iptvnator don't start at Linux Mint.

### ISSUE THREAD

**Issue by gr3ym1nd** [4gray/iptvnator#138]
iptvnator don't start at Linux Mint.
I've installed iptvnator version 0.10.0

When i type into the shell ~$  iptvnator
I become only this error message :

iptvnator: error while loading shared libraries: libdrm.so.2: cannot open shared object file: No such file or directory

libdrm2 is installed.
The linux system is always up to date
Hardware is inteli7 gen10
No additional graphics card.

**Comment by 4gray** [comment]
How did you install the application, did you use deb, snap or appimage?

**Comment by gr3ym1nd** [comment]
I've used the deb file from

https://github.com/4gray/iptvnator/releases

**Comment by Axel-Erfurt** [comment]
What is your Mint Version? I have 20.3 xfce and it works fine.

**Comment by what-a** [comment]
I too am running Linux Mint 20.3 Xfce and IPTVnator works fine.
