### ISSUE TITLE
Unable to run application on Ubuntu Budgie 20.10

### ISSUE THREAD

**Issue by rainer2208** [4gray/iptvnator#14]
I have installed the snapp application, but it doesn't open when clicking on it.

**Comment by 4gray** [comment]
Hi, @rainer2208 which version of the application do you use?
Could you please try to start the app from the command line with `snap run iptvnator` to check whether there are any errors?

**Comment by rainer2208** [comment]
Hi, @4gray, I have tried running the app with with "snap run iptvnator", but it won't open, neither throw any error messages. 

"sudo snap run iptvnator" returns : mkdir: cannot create directory '/run/user/0': Permission denied. Does this help? 

The version is 0.3.0

**Comment by 4gray** [comment]
Thanks.
It looks like a snap permission problem, please check this one, it looks very similar: https://askubuntu.com/questions/1009698/permission-for-snap-applications

**Comment by rainer2208** [comment]
Hi, checked out the link you posted and the install worked with `snap install notepadqq --devmode` (uninstalling the prior version first). 

Thanks for your support.
