### ISSUE TITLE
Load playlist

### ISSUE THREAD

**Issue by linuxubuntu63** [4gray/iptvnator#140]
Hello.
Thanks for your job.
Unfortunatly i can't load my playlist of my provider.
My playlist is text like that:
https://xxxxxxx.xx/get.php?username=xxxxxxxx&password=xxxxxxx&type=m3u_plus&output=ts

Can you help me please ?
Thanks a lot

**Comment by linuxubuntu63** [comment]
Any help please ?

**Comment by leknoppix** [comment]
I think I have the same problem as you.
According to my research, the type of header should be changed because our playlists do not accept browser headers (html/js). You should be able to add the VLC header.
But how, I don't know.

**Comment by 4gray** [comment]
The link looks like a xtream code playlist, this format is currently not supported by the player.
