### ISSUE TITLE
What the heck happened to the UI?

### ISSUE THREAD

**Issue by jaigitrep159** [4gray/iptvnator#146]
**Describe the bug**
So when i just viewing the EPG, and it did screwed the UI. The Minimize, Maximize, and Close, are disappeared.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/76834328/173334952-d4347cf4-f129-4787-a51e-7016a6b5487a.png)
**Desktop (please complete the following information):**
 - Electron
 - OS: Windows 10 Build 19044.1706

**Additional context**
Please fix this...

**Comment by Axel-Erfurt** [comment]
Maybe just a Windows problem?

The error does not occur in Linux.

**Comment by 4gray** [comment]
Should be fixed in the new version (v0.11.0).
