### ISSUE TITLE
Media cloud not be loaded, either becuase the network failed or because the format is not supported.

### ISSUE THREAD

**Issue by ProTechEx** [4gray/iptvnator#157]
Hi,

i am running iptvnator v0.1.0 under Windows 10. It does load the content of the Playlist but unfortunately doesn't play them.
VLC Player does play the same playlist streams without any issue.
![image](https://user-images.githubusercontent.com/5677301/182792651-9485572a-4cb0-429c-b7dd-3fbde4c98233.png)

**Comment by ProTechEx** [comment]
no ideas ?

**Comment by Axel-Erfurt** [comment]
What is it? mp4, m3u8, ts ... ?

**Comment by borisorlov21** [comment]
great turned out nothing superfluous well done

**Comment by 4gray** [comment]
Iptvnator is based on electron/chromium, so unfortunately not all formats and codecs that work in vlc and other native players are supported within the browser.
