### ISSUE TITLE
Ignores covert channel #

### ISSUE THREAD

**Issue by bamper45** [4gray/iptvnator#158]
**Is your feature request related to a problem? Please describe.**
Yes/No

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

_I would like to understand the # argument before url. This means the channel is hidden_

**Comment by 4gray** [comment]
Don't know if this is part of the m3u specs. In any case, the player uses this library github.com/freearhey/iptv-playlist-parser#readme, which doesn't seem to support this.
