### ISSUE TITLE
Feature request: mpegts support

### ISSUE THREAD

**Issue by fanthos** [4gray/iptvnator#172]
**Is your feature request related to a problem? Please describe.**
I am using udpxy to convert my multicast IPTV to unicast HTTP IPTV. Using mpegts player can work with udpxy and my iptv provider. Currently iptvnator and hls.js video.js not support mpegts.

**Describe the solution you'd like**
There are some transmuxer like mpegts.js makes the stream playable in browser:
[mpegts.js](https://www.npmjs.com/package/mpegts.js)
videojs plugin:
[videojs-mpegtsjs](https://www.npmjs.com/package/videojs-mpegtsjs)
source code: https://cdn.jsdelivr.net/npm/videojs-mpegtsjs@1.0.0/src/plugin.js

**Describe alternatives you've considered**

**Additional context**

**Comment by glennlunder** [comment]
My IPTV provider only delivers ts-type streams, that currently do not play in IPTVNator. Would love to use the app, if it was possible.

The url I have has &output=ts&type=m3u_plus appended at the end of the url.

**Comment by glennlunder** [comment]
The v0.13.0 has solved my issue with its mpv player support - my iptv now plays beautifully. 👍🏻

**Comment by 4gray** [comment]
@glennlunder very glad to hear that! :)
