### ISSUE TITLE
not able to fetch epg from xml file

### ISSUE THREAD

**Issue by bendschs** [4gray/iptvnator#177]
my XML file (see attachment, only zipped for uploading to github) does not seem to be recognized. it works very well with kodi-iptv but in iptvnator it seems to be stuck at "fetching". apparently it does not matter wether i host it on an http server or just point the configurator to the file by using "file:///path/to/xml".  
any idea what could be wrong, is it maybe the structure auf the xml-file2?
[guide.xml.zip](https://github.com/4gray/iptvnator/files/9734133/guide.xml.zip)

**Comment by 4gray** [comment]
Thank you for the feedback. I will check the issue, probably it's related to the epg-parser library that is used in IPTVnator.

**Comment by bendschs** [comment]
perfect! the xml is based on telerising.

**Comment by bendschs** [comment]
can confirm it works with the latest version. congrats and thank you 🙏
