### ISSUE TITLE
Electron Wrapper with shortcut to close

### ISSUE THREAD

**Issue by bendschs** [4gray/iptvnator#181]
On MacOS it's quite handy to close fokused windows with command+q. This does not seem to be possible with the current configuration of how the electron wrapper is built.

**Comment by bendschs** [comment]
thank you for implementing this. it's working but one thing that actually makes it counter productive is, that the iptvnator window never looses focus. so for instance if i have it open switch to another application that i want to close by pressing command+q it's always the iptvnator window being closed, no matter how many other applications i switch to before doing that.

cheers
bendsch

**Comment by 4gray** [comment]
Oh yes, my bad, just registered the hotkey globally instead of at the application level. It will be fixed in the next version 👍

**Comment by bendschs** [comment]
👍 thank you so much!

**Comment by 4gray** [comment]
should be fixed in v0.13.0 https://github.com/4gray/iptvnator/releases/tag/v0.13.0
