### ISSUE TITLE
Channel Logos

### ISSUE THREAD

**Issue by what-a** [4gray/iptvnator#193]
When scrolling up and down a long channel list (e.g. 250 channels) some logos disappear and then reappear, then disappear again. I'm guessing IPTVnator is attempting to reload them from the internet as I scroll up and down. Instead, could IPTVnator cache the logos locally and then search the local cache first before attempting to re-download from the internet? 

Below is an example were all stations use the same logo but due to scrolling up and down the channel list, IPTVnator dropped the logo for the Phoenix station despite it being the exact same logo used for all.
![image](https://user-images.githubusercontent.com/88639906/204053600-9e1b36a3-ef8c-422a-bd15-5630b67ee315.png)

**Comment by Axel-Erfurt** [comment]
You can use local icons in your playlist.

tvg-logo="/path/to/logo.png"

**Comment by what-a** [comment]
Axle, thanks for the suggestion.
BTW, after further experimenting it seems the issue of logos disappearing is not due to them being local vs a remote server, but rather to do with one or more of them being off line. As long as all logos are linked correctly and available then they all appear fine even when vigorously scrolling the channel list. However, if one (or some) are offline, then it will result in others not displaying (above and beyond those that are off line).

**Comment by 4gray** [comment]
There is something like lazy loading in the channels list, I'll need to test the implementation in more detail. 
But I don't think it's too critical, is it?

**Comment by what-a** [comment]
No, not critical.

**Comment by 4gray** [comment]
If I remember correctly it was fixed in 0.14, if not feel free to re-open the issue again
