### ISSUE TITLE
m3u playlist not loading

### ISSUE THREAD

**Issue by firofame** [4gray/iptvnator#194]
**Describe the bug**
this m3u playlist is not loading https://raw.githubusercontent.com/firofame/Malayalam-IPTV/main/iptv.m3u

**To Reproduce**
1. Go to https://iptvnator.vercel.app/
2. Click on add via url
3. add this url - https://raw.githubusercontent.com/firofame/Malayalam-IPTV/main/iptv.m3u
4. See error in the console

**Expected behavior**
videos should work

**Comment by 4gray** [comment]
It's related to the CORS error, please try with the electron app.

**Comment by firofame** [comment]
is that expected since the app is using a cors proxy?

**Comment by 4gray** [comment]
Yes, it's expected. The proxy is only used to upload playlists, but not for the streams themselves.
