### ISSUE TITLE
RAM load

### ISSUE THREAD

**Issue by nobef** [4gray/iptvnator#195]
Version 0.11.1
Windows 11 x64, 16GB RAM

![изображение](https://user-images.githubusercontent.com/77186394/205321842-68aefed5-f72e-4d2b-8665-1bd3be882714.png)

**Comment by 4gray** [comment]
=> electron app. or do you see any serious memory leaks in the angular part?

**Comment by jezokshe** [comment]
@4gray I do not understand, I thought that this might not be normal and reported.

**Comment by 4gray** [comment]
I agree, in general this is not normal, but unfortunately typical for an electron based application. 

I was looking at [tauri](https://github.com/tauri-apps/tauri) as a replacement for electron, but I think there may be unpredictable issues with the player on different platforms...

**Comment by jezokshe** [comment]
@4gray Yes, I am a complete zero in this, but I have seen that some are even proud that their application does not use such code.
![изображение](https://user-images.githubusercontent.com/77186394/211913059-b021124b-ebaf-4d4b-85f3-a0584118d3dd.png)

**Comment by 4gray** [comment]
Please try the latest beta version, it should use noticeably less memory, please leave your feedback after testing.
