### ISSUE TITLE
Does not load m3u list 

### ISSUE THREAD

**Issue by fruizaviles** [4gray/iptvnator#210]
Does not load the list 
https://iptv-org.github.io/iptv/index.nsfw.m3u
it gets permanently loading database but does nothing, nor loads it when the m3u link is added, see screenshot:

![Screenshot_2023-01-04-11-45-02-927-edit_com android chrome](https://user-images.githubusercontent.com/26512079/210538548-6c5fc0ea-afab-4958-a659-776fffe0c006.jpg)

So then, you cannot use update list feature because you have to load it as file. See difference among m3u and m3u8 lists update feature shown in the attached screenshot. 

![Screenshot_2023-01-04-11-48-04-801-edit_com android chrome](https://user-images.githubusercontent.com/26512079/210539045-9cddeb42-3f31-4489-b25c-10819e8eb33b.jpg)

**Comment by 4gray** [comment]
Thanks for the feedback. Is this happening on the website in the PWA or in the electron app?

**Comment by fruizaviles** [comment]
Hi there. It happens in both. Yesterday tried in Amazon Silk and also fails.
Cheers,

Frank

**Comment by Axel-Erfurt** [comment]
This playlist loads for me with no problems. Linux LMDE5, iptvnator 0.11.1
![nator2](https://user-images.githubusercontent.com/2623542/211499680-a0fc2ba6-5053-4de5-a289-1d6045524b51.png)

**Comment by Axel-Erfurt** [comment]
In https://iptvnator.vercel.app/ , It only works there if I save the playlist locally and then load it.

**Comment by fruizaviles** [comment]
Hi there. Does not work for me. Neither Android 12 Miui 13 and everything
updated to latest versions, nor on Amazon Silk on a Fire TV Stick versión
2021 updated to latest firmware. Do not know what may happen then.
Cheers

**Comment by 4gray** [comment]
PWA backend returns 413 error, this is due to file size and vercel limit (4mb). Unfortunately there is nothing I can do about this, but a self-hosted version for the web application is coming, see: https://github.com/4gray/iptvnator-backend.

In the electron based app the URL upload works correctly.
