### ISSUE TITLE
Docker image doesn't work on amd64 architecture

### ISSUE THREAD

**Issue by madejackson** [4gray/iptvnator#212]
**Describe the bug**
Like commented here: [Link](https://github.com/4gray/iptvnator/discussions/211), the newly announced Docker image only works on arm64 like a raspberry pi. Doesn't run on amd64

**To Reproduce**
Try to run docker image on an x86 or amd64 machine.

**Expected behavior**
Should run nicely

**Desktop (please complete the following information):**
 - PWA application
 - OS: unraid 6.5.11

**Comment by 4gray** [comment]
Ah, true, didn't think of that. I was building locally on a M1 MacBook, so arm. Will set up GitHub actions soon to build docker images from there.

**Comment by madejackson** [comment]
Thx, I can confirm it now runs on unraid 👍
