### ISSUE TITLE
Save chnages settings doesn't work

### ISSUE THREAD

**Issue by trimechee** [4gray/iptvnator#215]
Hello, I download and instal windows 10 version our beloved IPTVnator and i tried to change language and video player and theme but the "save changes" button doesn't work and changes aren't registered.

**Comment by 4gray** [comment]
Hi, thanks for the feedback! 
Does the issue still exist? Are you using the latest version?

**Comment by trimechee** [comment]
Yes, the issue still exist, I am using only the latest version of IPTVnatorv0.11.1 for windows and I only installed one version of IPTVnator because I installed it a few days ago so I only used the latest version and the "save changes" button is greyed out and inactive from the beginning even before i make  changes to theme and video players, i am using latest microsoft visual c++ and latest windows 10 22H2 build 19045.2364 , but I specify that I disabled some windows features which I do not use to make my notebook more faster....

**Comment by 4gray** [comment]
Sadly I have no opportunity to check on Windows, but on macOS and in the PWA, everything works as intended.
![Monosnap screencast 2023-01-22 23-19-07](https://user-images.githubusercontent.com/1503032/213943430-1bfed742-d7db-492c-b207-c966a1384510.gif)

**Comment by trimechee** [comment]
There is no problem :)  I think it is not a serious problem because videojs player is the main player and I was able to play iptv without any problems and in addition IPTVnator used the dark theme which I prefer so I think it doesn't matter if I can't change the settings because IPTVnator works perfectly by default without the need to change the settings ! Thank you !

**Comment by Wasilewskiii** [comment]
+1 from me on this issue. You cannot change any settings (I am on Windows 11 21H2 Build 22000.1455) because the save changes button is just greyed out.

**Comment by Wasilewskiii** [comment]
I found out that the issue is that if you don't enter an EPG URL, you can't save your changes because it's treated as a required field even though it's not marked as such. To resolve this, use the "-" icon to remove the EPG URL input field and you'll be able to save your settings.

**Comment by trimechee** [comment]
@Wasilewskiii Wonderful Extraordinary gorgeous !! that's  works perfectly, i can change the settings ! thank you very much for your precious  help ! 🥇 💯   Effectively I do not see the usefulness of epg and I like to have the pleasure of discovering the content of tv channels by myself without epg  so I deleted or modified the default options to delete the epg and so that our bleoved Iptvnator will be more  faster ! 
@4gray now we hope  please that our beloved Iptvnator 🥇  will add option to choose user agent contained in a list beacuase i have discovered this huge chinese wiki containing huge iptv resources : 

https://github.com/imDazui/Tvlist-awesome-m3u-m3u8

and i think choosing a user agent might be necessary to make all these streams work without bugs and i don't know how to add or choose the right user agents ! thanks a lot !

**Comment by 4gray** [comment]
@trimechee @Wasilewskiii Thanks for the testing and feedback guys. Already fixed this behavior and I'll try to release a new version asap.

Regarding the user agent, let's discuss in another thread

**Comment by trimechee** [comment]
Yes of course ! :) Thank you 💯 🥇

**Comment by trimechee** [comment]
Yeah great news ! i submet and resquest again to videohelp to add Iptvnator and finally they add it ! https://www.videohelp.com/software/IPTVnator

**Comment by 4gray** [comment]
@trimechee thanks for sharing!
