### ISSUE TITLE
Remeber the size of home startup windows and move boobkmarks

### ISSUE THREAD

**Issue by trimechee** [4gray/iptvnator#217]
Hello, I installed IPTVnator on windows 10 and I maximize the window size and then I close IPTVnator then I open it but the software does not remember the maximum window size so I  click again to put the window in size maximum at startup of software, i hope IPTVnator will remember the size of startup windows and I hope there will be the possibility of moving the bookmarks to change the position of the bookmarks, thank you !

**Comment by what-a** [comment]
In Windows 10, right click, open properties, choose Run: Maximized.
![image](https://user-images.githubusercontent.com/88639906/212809913-c3f25371-8e20-4ace-b7f3-2a16d174cd6c.png)

**Comment by trimechee** [comment]
Awesome ! Thank you very much @what-a :) 💯 sorry for the delay, I don't know why I didn't see the notification or received notification of your answer :( I saw the label "enhancement" so i click and i discover yout answser....

**Comment by 4gray** [comment]
The channels in bookmarks list are draggable now, see https://github.com/4gray/iptvnator/commit/ba41c8dae5e82bd1f39fb9a6cd8518e25dcdb894

**Comment by trimechee** [comment]
Awesome ! Thank you :) 🥇
