### ISSUE TITLE
User agent 

### ISSUE THREAD

**Issue by trimechee** [4gray/iptvnator#223]
Hello, I noticed in the settings, there is an option "add a user agent because some streams don't work without a user agent", I don't know how to add and which user agent to choose, user agent of android tv or google tv ? it will be great to make things easier to add presets, a kind of list of different user agents of various and different devices so we can try and see which use agent works, thank you so much !

**Comment by 4gray** [comment]
Hi, since there are many values and the user-agent can be anything, an arbitrary input field is used. To find the right option for the playlist, you need to understand what value the provider expects.

**Comment by trimechee** [comment]
Very Interesting ! Thank you ! I will try to undestand which playlist i use and which user agent choose but for the moment, my playlist works normally and without problem and no needing to choose a uger agent for the moment........thank you again for your awesome efforts to make this wonderful software :) 🥇
