### ISSUE TITLE
GUI translation issues

### ISSUE THREAD

**Issue by bovirus** [4gray/iptvnator#226]
**Describe the bug**
Issue about GUI translation

**To Reproduce**

See screenshot

**Expected behavior**

Fix the issues

**Screenshots**

![image](https://user-images.githubusercontent.com/1262554/217909163-8ec047cd-20d7-42c5-9140-7263ee5560f7.png)

**Desktop (please complete the following information):**
 - PWA or Electron application (https://iptvnator.vercel.app/)
 - OS: Windows 10 22H2 64bit
 - Browser Chrome 110.0.5481.78  64bit
 - Version 0.1.11.0

**Additional context**

@4gray 

Please check

**Comment by 4gray** [comment]
Thanks for the tip. Extracted translations into the language file, see: https://github.com/4gray/iptvnator/commit/e9229cb162fe8393e13e8a4a7b002dbcae91fa3b

I left the player names as they are, I think they don't need to be translated. I would be glad if you could add new translations for Italian.

**Comment by bovirus** [comment]
@4gray 

Please check the screenshot after compòile latest version with my changes for italian

![image](https://user-images.githubusercontent.com/1262554/218256521-228b57ca-c60b-4412-a9db-22fe630af3d4.png)

It seems that there is a string untranslated.

Thanks.

**Comment by bovirus** [comment]
@4gray 

No changes about GUI?

**Comment by 4gray** [comment]
@bovirus extracted the strings which you mentioned above, see [refactor(settings): extract hardcoded text to i18n string](https://github.com/4gray/iptvnator/commit/4ce405a8bf94310eab678b08a4fa1c7fea427920). 

Regarding `You are using the latest version` - this one is translated, but it only refreshes after switching the language and reloading the page. I'll check later what's the reason for the issue.

**Comment by bovirus** [comment]
@4gray 

Sorry for the question: how can check the update (new program version)?

**Comment by 4gray** [comment]
Thanks for the PR!
