### ISSUE TITLE
keine m3u

### ISSUE THREAD

**Issue by donald2587** [4gray/iptvnator#231]
hallo jungs 
kann es sein das der player keine 
http://domain:port/username/password/sendernr  <--- links abspielen kann 

gibt es dafür eine lösung ? 

danke 

vg

**Comment by 4gray** [comment]
Hey, nicht wirkich :-/ 
Wird die Playlist importiert, also sieht man die Senderliste in der Sidebar oder gar nichts?

**Comment by donald2587** [comment]
hi 
danke für die antwort
ja wird geladen
list ist da... auch die sender logos... epg auch
drücke ich auf den sender fängt er an zu laden ich sehe das mein netspeed auf ca 1-2mb/s hoch geht aber nach ca 20 sekunden war es dann und fehler kommjt dann das er es nicht wieder geben kann
danke

**Comment by 4gray** [comment]
Scheinbar wird der Stream nicht unterstützt. Falls weiterhin Interesse besteht, kannst gerne die neueste [0.13 Version](https://github.com/4gray/iptvnator/releases/tag/v0.13.0) ausprobieren mit der mpv-Player-Intgration. Ich könnte mir vorstellen, dass es damit klappen könnte.

**Comment by donald2587** [comment]
danke damit geht es ;) 
schoenes we
