### ISSUE TITLE
HLS.js

### ISSUE THREAD

**Issue by trimechee** [4gray/iptvnator#232]
Hello, i discover this awesome software integrated in many iptv players : HLS.js is a JavaScript library that plays HLS in browsers with support for MSE, it will be great to integrate this tool to our beloved Iptvnator, thank you !

https://github.com/video-dev/hls.js#player-integration

**Comment by 4gray** [comment]
IPTVnator uses this library under the hood 👍

**Comment by trimechee** [comment]
Awesome !! 💯 🥇
