### ISSUE TITLE
404 response when adding m3u URL PWA RPI version 

### ISSUE THREAD

**Issue by easyicetrusty** [4gray/iptvnator#233]
**Describe the bug**
 I am getting a 404 response when trying to add m3u URL. 

**To Reproduce**
1. Run 'docker-compose up -d'. Back and Front end Ok
2. Add m3u URL. 
3. 404 Response
4. Started backend 'docker run -p 3333:3000 -e CLIENT_URL=http://192.168.8.226:4333 4gray/iptvnator-backend' --> Ok 
5. 192.168.8.226:4333 --> Getting Hello World 

**Expected behavior**
If back and front end started apparently Ok, should be able to load m3u URL

**Screenshots**

**Desktop (please complete the following information):**
 - PWA 
 - OS Linux
 - Browser Firefox 
 - Version 110

Context: Access to Remote  Raspberry Pi where PWA is running. No Firewall. Ports Open.

**Comment by 4gray** [comment]
Regarding the 3. step, could you please open the network tab from dev tools in your browser and check the request url/port?
