### ISSUE TITLE
Need download playlist

### ISSUE THREAD

**Issue by error-500** [4gray/iptvnator#234]
**Is your feature request related to a problem? Please describe.**
iptv-org/iptv repo was closed. I have downloaded and worked playlist by url on my computer. I need move data to an other computer 

**Describe the solution you'd like**
Better solution add export button in playlist settings popup 

**Additional context**
![image](https://user-images.githubusercontent.com/15867628/222930935-c0cd61f6-bae3-40ca-ab75-98fc0631b007.png)

**Comment by 4gray** [comment]
The feature was implemented in https://github.com/4gray/iptvnator/commit/7e4d6b171fa87ffb7084344a10d653dd2cb30ea2
