### ISSUE TITLE
update docker?

### ISSUE THREAD

**Issue by bendschs** [4gray/iptvnator#243]
question: how is the self hosted pwa-docker being updated? 
i tried to build front- and backend after pulling from git and then did "docker-compose pull". neither of that seemed to update the docker to the most recent version (released the day before yesterday).

is the docker not being updated by pulling from git repo or how does it work?
sorry, not exactly familiar with docker yet.

cheers,
bendsch

**Comment by 4gray** [comment]
Good point, at the moment the process is semi-automated and I need to run the docker image release manually. Also, versioning needs to be set up as all images are currently released under the "latest" tag.

**Comment by Chopp3rDave** [comment]
Is there any update on this? I'd love to get my docker image updated. Anything I can do to help out?

**Comment by 4gray** [comment]
The docker images were updated - https://hub.docker.com/u/4gray
