### ISSUE TITLE
IPTVnator 0.13.0 - Translation issues

### ISSUE THREAD

**Issue by bovirus** [4gray/iptvnator#247]
**Describe the bug**

Please check screenshot

**To Reproduce**

**Expected behavior**
Fixz the issues

**Screenshots**

At first run apepar this crimage cuuted

![image](https://user-images.githubusercontent.com/1262554/227517439-eaab52ae-93f5-4586-b0c0-56a6b4ecd6ec.png)

String untranslated

![image](https://user-images.githubusercontent.com/1262554/227517497-49bfa2a8-643a-4cad-a7ef-ba4ac641c174.png)

Strings untranslated

![image](https://user-images.githubusercontent.com/1262554/227517608-6ed12c1a-be77-46c6-93cf-fe8bda3aa52a.png)

**Desktop (please complete the following information):**
 - PWA or Electron application 0.13.0 Windows installer
 - OS: Windows 10 22H2
 - Browser Chrome
 - Version 0.13.0

**Additional context**

**Comment by 4gray** [comment]
It's my mistake, the part of the translation that you added in the last pull request I accidentally left out in v0.13, sorry 🤦  It will be part of the next release.

**Comment by 4gray** [comment]
the new translations are part of v0.14.0 - https://github.com/4gray/iptvnator/releases/tag/v0.14.0
