### ISSUE TITLE
MPV installation and players based on mpv

### ISSUE THREAD

**Issue by trimechee** [4gray/iptvnator#248]
Hello, thank you so much for addinf support of Mpv player !! 🥇 💯 
I followed the instructions to install mpv : 

https://github.com/4gray/iptvnator/wiki/What-is-mpv-video-player-and-how-to-install-it-on-different-operating-systems%3F

and i donwload and install bat file contained in
  bootstrapper.zip

https://sourceforge.net/projects/mpv-player-windows/files/latest/download

and a command prompt cmd window opens and installs mpv but I notice that there is a message "do not run this script while being an administrator", and I am using my windows 10 pc as an administrator and I have disables my anti virus for more speed, so have I been infected by a virus and malware by installing mpv player ?

concerning mpv, here are 4 excellent mpv gui players optimized for windows, linux ... and having many exceptional options, we hope these players based on mpv will be supported by our beloved Iptvnator in the future :)

https://coslyk.github.io/moonplayer.html

https://tsl0922.github.io/ImPlay/

https://github.com/mpvnet-player/mpv.net

https://github.com/mpvnet-player/mpv-gui

**Comment by bendschs** [comment]
on the newer mac os operating systems and on silicone homebrew changed their root path to "/opt/homebrew/".
is there a way to manually point iptvnator to the executable mpv (/opt/homebrew/bin//mpv) ?

**Comment by 4gray** [comment]
@bendschs I developed and tested on a M1 MacBook (macOS Ventura 13.2.1), also installed mpv via brew, no additional configuration was required. 
Have you tried running `mpv` from the terminal, just using the mpv command? It's important that homebrew is specified in your $PATH (https://sourabhbajaj.com/mac-setup/Homebrew/), because [node-mpv](https://github.com/j-holub/Node-MPV) library which is used in iptvnator takes the path from there. 

@trimechee Thanks for the feedback. I don't have a chance to test under windows at the moment :/ Perhaps someone else has tried mpv+iptvnator using windows?

**Comment by trimechee** [comment]
@4gray Thank you :) when i saw the warning, i I cancelled the installation of the script that installs mpv, and i downloaded the latest stable version of mpv via this link from this famous site so no more need to install script or dig into beta version on sourceforge...

https://www.videohelp.com/software/mpv-media-player

maybe it will be a good idea to add a second new version of Iptvnator which already contains the executables of mpv player : a special version which contains modifications allowing mpv or other players to integrate more easily with Iptvnator....

**Comment by bendschs** [comment]
in the terminal everything works as expected (see output).
the path environment is also set like suggested by brew (brew doctor would throw an error message if it was not).

iptvnator still does not seem to find mpv though (see screenshot).
```
Benno@B2 ~ % mpv
mpv 0.35.1 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Sat Jan 28 04:49:47 2023
FFmpeg library versions:
   libavutil       57.28.100
   libavcodec      59.37.100
   libavformat     59.27.100
   libswscale      6.7.100
   libavfilter     8.44.100
   libswresample   4.7.100
FFmpeg version: 5.1.2

Usage:   mpv [options] [url|path/]filename

Basic options:
 --start=<time>    seek to given (percent, seconds, or hh:mm:ss) position
 --no-audio        do not play sound
 --no-video        do not play video
 --fs              fullscreen playback
 --sub-file=<file> specify subtitle file to use
 --playlist=<file> specify playlist file

 --list-options    list all mpv options
 --h=<string>      print options which contain the given string in their name

Benno@B2 ~ % which mpv
/opt/homebrew/bin/mpv
Benno@B2 ~ % brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libDellMonitorSdkLib.dylib
  /usr/local/lib/libcpsrt.dylib
  /usr/local/lib/libwkextmac.dylib
```
![Bildschirm­foto 2023-03-25 um 22 16 39](https://user-images.githubusercontent.com/17085451/227742436-03fa6766-f879-4646-ac87-878a1124f3b8.png)

**Comment by VincentDugard** [comment]
hello, same problem here, mpv installed using homebrew, cli is working but iptvnator say it's not installed

**Comment by seb81** [comment]
Hi. Same problem. MacOS 13.3 (22E252). Iptvnator and mpv installed by homebrew.
`brew install --cask iptvnator`
`brew install --cask mpv`

**Comment by martingouy** [comment]
For people having problems on M1 macs with IPTVnator not able to find `mpv`, here is a "hacky" fix:
1. Install `mpv` with homebrew
2. Get the path of the binary: `which mpv`. Copy the path (ex: `/usr/local/bin/mpv`)
3. Modify these lines in the IPTVnator code source:
https://github.com/4gray/iptvnator/blob/47bf91b099bf0914ec126968e19b5f4b63ad18e7/electron/api.ts#L41
with:
``` typescript
const createMpvInstance = () => new mpvAPI({
    "binary": '[PATH OF THE BINARY]',
}, ['--autofit=70%']);
```
4. Build IPTVnator again (https://github.com/4gray/iptvnator#how-to-build)


Hopefully, IPTVNator should now be able to find `mpv`

**Comment by 4gray** [comment]
@martingouy thanks for the tip! 
Has anyone tried it? If it works, I'll add the option of specifying the path in the settings.

**Comment by berkaycagir** [comment]
I'm having the same issue as well; if launched from Finder, IPTVnator fails to launch mpv. However, when I start IPTVnator manually (e.g. invoking `/Applications/iptvnator.app/Contents/MacOS/IPTVnator` from the Terminal), on the first channel opening, Terminal asks for microphone permission (I have no clue why) and mpv launches successfully afterwards.

**Comment by 4gray** [comment]
Please try it with v0.14.0 - https://github.com/4gray/iptvnator/releases/tag/v0.14.0

**Comment by jaaacck** [comment]
I am experiencing the same thing with v0.14.0 where it fails to load MPV. I've installed MPV both from source and via brew with no luck. I've explicitly set the path as well as moved to a custom location with the same error.

The only way (using $PATH) is to launch via command the same as @berkaycagir - `/Applications/iptvnator.app/Contents/MacOS/IPTVnator`. I don't however get asked for microphone permissions when doing this. Once launched via cli it works without issue.

2023 MPB 14 Inch M2 - OS 13.4 (22F66)

**Comment by trimechee** [comment]
Ohhh this so marvellous amazing !! Thank you so much @4gray for all these new awesome features and bug fixes :) 💯 🥇

**Comment by lucasmd** [comment]
Hey @4gray,
Do you think it can works using IINA ? Which is really the best player for mac so far :https://github.com/iina/iina and it's based on MPV ?

**Comment by mtomsic** [comment]
Seems to work if using this:
https://github.com/vitorgalvao/mpv-dummy/
