### ISSUE TITLE
A javaScript error occured in the main process

### ISSUE THREAD

**Issue by NabilKhalaf** [4gray/iptvnator#257]
Hello , I use IPTV NATOR with MPV PLAYER, This works well but I have an error, I leave you the message so you can see what's wrong with my setup. 

![image](https://user-images.githubusercontent.com/22280252/229359357-94bdd82a-5606-461d-9f55-f313ee07b6aa.png)

Thank your for your feedback

**Comment by eplinux** [comment]
Same here, exactly the same issue. It's working nonetheless but the error keeps popping up and makes watching a stream in fullscreen mode impossible. Context: using mpvplayer, installed it via scoop.

**Comment by 4gray** [comment]
fixed in v0.14.0 - https://github.com/4gray/iptvnator/releases/tag/v0.14.0
