### ISSUE TITLE
Problem with http m3u8 on web

### ISSUE THREAD

**Issue by andreacocci95** [4gray/iptvnator#269]
**Describe the bug**
I receive error on web version of Iptvnator when I try to play http live stream urls. The url works because if I past it on vlc it is correctly reproduced.

**To Reproduce**
1. Go to https://iptvnator.vercel.app/
2. Click on 'Import as text'
3. Paste this:

    ```
    #EXTM3U
    #EXTINF:-1,[1] TEST
    #EXTVLCOPT:http-user-agent=Mozilla/5.0
    http://wms.shared.streamshow.it/canale51/canale51/playlist.m3u8
    ```
    then click on 'Import'
5. Try to play the channel and see the error

**Expected behavior**
I want to reproduce http url like https urls.

**Comment by 4gray** [comment]
The application is deployed in http**s**:// context, but the stream domain is using http://, see: https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content 

There are two possible solutions:
1. Self-host the app locally in http context
2. Use desktop (electron-based) version of the app

**Comment by andreacocci95** [comment]
I tried to self-host app locally in http context but I have CORS error. There is a way to add on header the value: 'Access-Control-Allow-Origin *'?

**Comment by andreacocci95** [comment]
I confirm, same problem on linux application.

**Comment by andreacocci95** [comment]
I run it with docker.

**Comment by 4gray** [comment]
Okay, check this docker-compose file please, there you can specify the client and backend urls with respective ports https://github.com/4gray/iptvnator/blob/electron/docker/docker-compose.yml 

Also feel free to check this issue for some configuration details and examples: https://github.com/4gray/iptvnator/issues/220

**Comment by andreacocci95** [comment]
Ok, I write wrong the backend url with http instead of https. Now URL of iptv list is loaded correctly.

**Comment by alanmilinovic** [comment]
Would it be possible to alternatively provide some form of transcoding/proxying of the HTTP stream through HTTPS so that the browser does not have to directly request an HTTP resource?
