### ISSUE TITLE
Support audio-only channels

### ISSUE THREAD

**Issue by microraptor** [4gray/iptvnator#271]
**Is your feature request related to a problem? Please describe.**
I can't play this playlist of radio channels: http://bit.ly/kn-kodi-radio
The list is maintained here: https://github.com/jnk22/kodinerds-iptv

**Describe the solution you'd like**
It would be awesome, if audio-only channels are supported for streaming radio stations. Instead of a video only the icon of the channel could be displayed.

**Describe alternatives you've considered**

**Additional context**
Thank you for this awesome project.

**Comment by Axel-Erfurt** [comment]
Radio stations are working for me (in Linux LMDE5) only using MPV Player.
However, they cannot be stopped because mpv has no window for audio only.
I then have to kill mpv.

**Comment by 4gray** [comment]
I added audio player for audio-only streams aka radio (based on `radio="true"` flag from the m3u file). It will be part of the next release, but could be tested in the PWA now: https://iptvnator.vercel.app/playlists?url=https:%2F%2Fraw.githubusercontent.com%2Fjnk22%2Fkodinerds-iptv%2Fmaster%2Fiptv%2Fkodi%2Fkodi_radio.m3u


![CleanShot 2023-08-21 at 19 38 35@2x](https://github.com/4gray/iptvnator/assets/1503032/e14209bc-4a02-48f1-ab14-3482a812a73e)
