### ISSUE TITLE
All Italian RAI channels do not work

### ISSUE THREAD

**Issue by pigeonskiller** [4gray/iptvnator#274]
As in title, all Italian RAI channels in free TV channels at https://raw.githubusercontent.com/Free-TV/IPTV/master/playlist.m3u8 do not work.
Please solve.
Thanks and have a nice day.

**Comment by 4gray** [comment]
Have you tried it with mpv player?

**Comment by pigeonskiller** [comment]
Hi, thanks you trying to help me.

It does NOT work in Windows 10, not even with MPV installed from the Microsoft store (see attachment).

Anyway RAI channels don't even work in Linux.

Why not use VLC instead of MPV?

Da: 4gray
Inviato: mercoledì 24 maggio 2023 12:20
A: 4gray/iptvnator
Cc: pigeonskiller; Author
Oggetto: Re: [4gray/iptvnator] All Italian RAI channels do not work (Issue#274)

Have you tried it with mpv player?

**Comment by 4gray** [comment]
I can start the stream with mpv on mac os, but there is an unavailability warning since I'm not in Italy.
![SCR-20230525-bfq](https://github.com/4gray/iptvnator/assets/1503032/750df153-1da5-477d-88d0-e907ebf407c8)

**Comment by pigeonskiller** [comment]
You lucky. It doesn’t work for me.

Da: 4gray
Inviato: giovedì 25 maggio 2023 08:36
A: 4gray/iptvnator
Cc: pigeonskiller; Author
Oggetto: Re: [4gray/iptvnator] All Italian RAI channels do not work (Issue#274)

I can start the stream with mpv on mac os, but there is an unavailability warning since I'm not in Italy.
