### ISSUE TITLE
Ubuntu Lunar 23.04 playlist from HDHomeRun can't be played

### ISSUE THREAD

**Issue by Paullux** [4gray/iptvnator#277]
**Describe the bug**
When I loaded my playlist IPTV from my HDHomeRun the channel reconized it the EPG works correctly but except with MPV the video did't started with player js (i have message in console about the incompatibility with the player) with html5 play the video did't started anymore (but there aren't except when i try to change of channel). 

**To Reproduce**
1. Create a playlist from hdhomerun
2. Load the playlist 
3. Choose the js player or html5 player
4. The video never started

**Expected behavior**
When I loaded my playlist IPTV from my HDHomeRun the channel reconized it the EPG works correctly but except with MPV the video did't started with player js (i have message in console about the incompatibility with the player) with html5 play the video did't started anymore (but there aren't except when i try to change of channel).

**Screenshots**
![image](https://github.com/4gray/iptvnator/assets/22844238/21ef8fa3-b690-46d7-8a89-e5463c81def1)

**Desktop (please complete the following information):**
 - snap version
 - OS: Kubuntu Lunar 23.04 
 - Browser google chrome
 - Version last version of snap store (i try it the last relesae from this repo but it's the same thing)

**Additional context**

**Comment by 4gray** [comment]
Unfortunately many video formats are not supported in js players, here it's a matter of electron/chrome. So the only solution today is to use mpv as a third party player.
