### ISSUE TITLE
unable to play xtreme code playlist.

### ISSUE THREAD

**Issue by NOOBNOOBOX** [4gray/iptvnator#279]
Just added xtreme code playlist using the website. it successfully added the playlist but when I play a channel it says playing in external player window,install mpv. mpv is already installed in my system I am assuming that this should be used in the iptvnator app where you can actually use mpv but in the app there seems to be no option for adding xtreme code. is it still in development or bug?

**Comment by 4gray** [comment]
Yes, it was in development. I recommend you to try the new electron based version of the app with mpv player - https://github.com/4gray/iptvnator/releases/tag/v0.14.0
