### ISSUE TITLE
Mpv path

### ISSUE THREAD

**Issue by trimechee** [4gray/iptvnator#283]
Hello, in the options of Iptvnator, there is a box to specify mpv path, please I don't know if I should put the executable "C:\mpv-0.35.1-x86_64\mpv.exe" or just the folder "C:\mpv-0.35.1-x86_64"? and do we have to put quotes to specify the path? Thanks a lot !

**Comment by gjstroom** [comment]
I was struggling with this as well, you need to list  "C:\mpv-0.35.1-x86_64\mpv.exe" and then restart Iptvnator.

**Comment by trimechee** [comment]
Great ! @gjstroom  Thank you so much for your precious help :)
