### ISSUE TITLE
Spinning wheel

### ISSUE THREAD

**Issue by fillilutten** [4gray/iptvnator#288]
**Describe the bug**
Can't play any channel. It's just stuck on spinning wheel. Using a m3u plus link. Tried html5 player and videojs player.

**To Reproduce**
1. Adding m3u link
2. Click a channel

**Desktop (please complete the following information):**
 - IPTVnator-0.14.0-universal.dmg
 - Mac OS Ventura 13.2

**Comment by IntrovertedFL** [comment]
Same issue here. I'm on Debian 11.

**Comment by 4gray** [comment]
Please try it with mpv player.
