### ISSUE TITLE
Window won't show

### ISSUE THREAD

**Issue by eplinux** [4gray/iptvnator#301]
**Describe the bug**

After a while, the program's main window stopped showing. While I can still hover over the icon in the tray and see a miniature version of the window, it won't appear anywhere on the screen.

**To Reproduce**
1. Open the app
2. App is started but no window is shown

**Expected behavior**
Seeing the main window

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**

**Comment by 4gray** [comment]
Please try to reinstall the app completely
