### ISSUE TITLE
Verification issue on MacOS Ventura

### ISSUE THREAD

**Issue by newspeer** [4gray/iptvnator#302]
**Describe the bug**
When I start the app MacOS Ventura 13.6 says that it can't verify the app.

**To Reproduce**
Start app on MacOS Ventura

**Expected behavior**
The app should start without failed verification message.

**Comment by Falloutman** [comment]
Same issue here on Mac OS 14.0

**Comment by zagnuts** [comment]
Have you tried going into system settings, then security settings, then approving the app to run? This is normal for any app installed outside the App Store, and you only have to do this once.

**Comment by newspeer** [comment]
That works! I didn't know about that feature. Thanks!

**Comment by newspeer** [comment]
This has been solved.
