### ISSUE TITLE
Feature Request: Auto Update

### ISSUE THREAD

**Issue by Mennaruuk** [4gray/iptvnator#31]
It'd be super super chill if IPTVnator can do daily checks on lists and redownload them as necessary. Not sure how this would work with favorites, but it'd be better than manually having the list removed and re-added. Thank you so much!

**Comment by 4gray** [comment]
Available in v0.7.0 now, see https://github.com/4gray/iptvnator/releases/tag/v0.7.0

**Comment by Mennaruuk** [comment]
**THANK YOU!!!!!**
