### ISSUE TITLE
Play .ts streams with VideoJs Player

### ISSUE THREAD

**Issue by newspeer** [4gray/iptvnator#342]
**Is your feature request related to a problem? Please describe.**
It is not related to a problem.

**Describe the solution you'd like**
I have an m3u file with some URLs ending with .ts
iptvnator's VideoJs Player does not play the channels wich URLs end with .ts

**Describe alternatives you've considered**
It works seamlessly in VLC, but I prefer using a build-in player over an external player

**Additional context**

**Comment by 4gray** [comment]
VideoJs has limits that prevent it from playing some formats, that's why third party players were added.
