### ISSUE TITLE
Docker setup is not the latest version (0.14.0 instead of 0.15.0)

### ISSUE THREAD

**Issue by schumi2004** [4gray/iptvnator#350]
I enrolled iptvnator using docker but the version i'm getting is version 0.14.0 instead of 0.15.0

How do i get the very latest version?

**Comment by bendschs** [comment]
can confirm this

**Comment by xtay573269555** [comment]
Same issue here. Hope to tag the version to images on docker hub.

**Comment by xtay573269555** [comment]
Additionally, there is another question. Is the `4gray/iptvnator-backend:latest` image on docker hub is the latest ? I don't know how to check it.

**Comment by begunfx** [comment]
@4gray any update on this?  It looks like the standalone docker version is still 14.  Thanks!

**Comment by zdaujdh** [comment]
@4gray wondering about this as well.  Looking to get this set up.

**Comment by tchirou** [comment]
Hi
Would it be possible to update docker to 0.15.1 ?
Thanks

**Comment by tchirou** [comment]
Hi
Any possibility to update it ?
Thanks

**Comment by 4gray** [comment]
The image was updated.
