### ISSUE TITLE
Error: something went wrong. Make sure that mpv player is installed onyour system. (status: 0)

### ISSUE THREAD

**Issue by ZAKhan** [4gray/iptvnator#351]
I have installed the app via snap store on Arch Linux. Have added valid streams but when playing a video it gives an error. I have tried all the players mentioned (giving exact path /usr/bin/ for  mpv and vlc) but nothing works and same error pops up.

**To Reproduce**
1. go to any video 
2. Click on Play 
3. See error

this is the exact error : Error: something went wrong. Make sure that mpv player is installed on your system. (status: 0)

![Screenshot from 2024-01-17 21-41-48](https://github.com/4gray/iptvnator/assets/2077923/8f618aa0-6af1-4a9f-b005-3745fbbd2823)

**Screenshots**
attached.

**Desktop (please complete the following information):**
 - snap
 - OS: Arch Linux
 - Version 0.15.0

**Comment by 4gray** [comment]
Try v0.15.1 please

**Comment by TravelTrader** [comment]
I have the same error, mpv and vlc installed.

Version 0.15.1
snap
Ubuntu 22.04

How can I solve it?

**Comment by sidewyz** [comment]
Version 16
Ubuntu 22.04
Snap 

Same problem
