### ISSUE TITLE
Archive and EPG not working with IPTV provider antifriz.tv

### ISSUE THREAD

**Issue by opteh** [4gray/iptvnator#353]
IPTV provider [antifriz](https://antifriz.tv/) has several m3u and Enigma2 playlists. 
![26-01-2024](https://github.com/4gray/iptvnator/assets/138050167/7ebacd96-9eaa-46af-9c6b-91ad1a417dd4)

They have three subcategories each (HLS, Mpeg-ts and T2). I tried all options, but I couldn't get the EPG to work, and most importantly the archive of TV programs. This operator has been working on my android tv for almost two years (Navigator OTT program). Could you please tell me the correct settings for this IPTV operator? Thank you in advance!

**Comment by 4gray** [comment]
I assume the link to the EPG is defined right in the playlist? If so, it is not currently supported.

**Comment by opteh** [comment]
Epg I can specify separately. I am more interested in correct display of channel names. And also what format from the above mentioned above should I choose? So that I can at least see the channel names and be able to use the archive.

**Comment by 4gray** [comment]
M3u (HLS) should be fine. How are the channels displayed now? Do you mean they are not displayed in the epg list or in general for viewing, on the left side?
