### ISSUE TITLE
 Backend Connection Issue

### ISSUE THREAD

**Issue by sdlkhfksl** [4gray/iptvnator#354]
The user is saying that they can normally use the IPTVnator app hosted at <https://iptvnator.vercel.app/>, but they encounter an error when trying to deploy their own version of the app at <https://iptvnator-eta.vercel.app/>. Specifically, when they click "add via url," an error message appears stating, "the back end is not reachable." They are asking for assistance in resolving this issue.

**Comment by 4gray** [comment]
Exactly, as @Deltwin mentioned, you need to separately build and deploy the backend for your instance.
