### ISSUE TITLE
DiscardVirtualMemory - KERNEL32.dll

### ISSUE THREAD

**Issue by Jhovannino** [4gray/iptvnator#357]
**Describe the bug**
Starting the application the following error appears: "The procedure entry point DiscardVirtualMemory could not be located in the dynamic link library KERNEL32.dll"

**To Reproduce**
1. Start the app
2. Boom, error appear

**Expected behavior**
Should start up without giving errors

**Desktop**
 - Electron application
 - OS: Win 7 Pro
 - Version 0.15

**Comment by 4gray** [comment]
Unfortunately the new electron version does not support windows 7.
