### ISSUE TITLE
0.1.5.1 - UI set as Italian - Strings in English

### ISSUE THREAD

**Issue by bovirus** [4gray/iptvnator#368]
@4gray 

**Describe the bug**

After install teh program I configured Italian language for GUI
But after re-launch application interface is in english.

**To Reproduce**

**Expected behavior**
UI in Italian -> strings in Italian

**Screenshots**

![image](https://github.com/4gray/iptvnator/assets/1262554/b1131531-7085-4bfc-94f4-53c9f29bf5bd)

**Desktop (please complete the following information):**
 - IPTVNator 0.51.1
 - OS: Windows 10 22H2 64bit Italian
 - Browser Google Chrome
 - Version 0.51.1

**Additional context**

**Comment by 4gray** [comment]
The issue was fixed here: https://github.com/4gray/iptvnator/pull/358 it will be included in the next release.
