### ISSUE TITLE
Add "cache" function to allow pauses and/or go back in a livestream

### ISSUE THREAD

**Issue by ghost** [4gray/iptvnator#37]
A "cache" function would be helpful to allow:
1) Go back a few seconds or minutes
2) Pause a livestreaming, and maintain a cache so that you can resume later.

Linux Mint developers created the "cache" function on Hypnotix and is really useful.
https://github.com/linuxmint/hypnotix

 Would it be possible to implement that feature in IPTVnator ?

Thanks for your great work !

**Comment by Axel-Erfurt** [comment]
I can press pause and it will continue playing from that point.
So it already seems to be working.
