### ISSUE TITLE
Icon for removing favorites not visible in the player.

### ISSUE THREAD

**Issue by momoRaza** [4gray/iptvnator#373]
I'm unable to remove a channel from favorites as the star icon is not visible anymore
I'm no the latest version 0.15.1 and on Arch linux. Please advise. 

Thanks
![Screenshot from 2024-04-01 06-28-00](https://github.com/4gray/iptvnator/assets/80984581/e7382cfb-65af-4c82-ab47-7dcb15963f10)

**Comment by 4gray** [comment]
That one was fixed in v0.16
