### ISSUE TITLE
changed playlists

### ISSUE THREAD

**Issue by Axel-Erfurt** [4gray/iptvnator#38]
Whenever I've edited a list, I have to delete it and add it again.

Isn't there a better solution?

**Comment by 4gray** [comment]
I think you mean something like the "auto-refresh" function, that is mentioned here #31, right?

Perhaps such a mechanism could be implemented as follows:
_1. Playlist added via URL:_ 
If a playlist was added via a link, just pull up a fresh file from the internet. 

_2. Playlist from the file system:_ 
In case the file was added from the file system, the full path to the file will be additionally saved with each added playlist. In this way, you will be able to modify the file with any text editor/IDE and update the playlists at every launch or start the updating process manually. 

Then there would be no need to delete and import the playlist multiple times.

As a second option, which I could also imagine in the future, is some basic functionality to edit the playlist directly from the player ГШ (remove/add a channel, rename, change sorting, etc.).  

If you have any other ideas or suggestions, I will be glad to hear them.

**Comment by Axel-Erfurt** [comment]
I only use local playlists.
**2.** would be perfect for me.

**Comment by 4gray** [comment]
Available in v0.7.0 now, see https://github.com/4gray/iptvnator/releases/tag/v0.7.0

**Comment by Axel-Erfurt** [comment]
fantastic!
