### ISSUE TITLE
Player for m3u playlists

### ISSUE THREAD

**Issue by jaliloup** [4gray/iptvnator#388]
**Describe the bug**
The players used for m3u playlists are very poor, it will be better to add exoplayer foa a better performance. 
Also it will be appreciated to add url for web sites.
Thank you

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - PWA or Electron application
 - OS: [e.g. Linux]

**Additional context**

**Comment by Axel-Erfurt** [comment]
Unfortunately, you don't even provide the most necessary information about your system.
