### ISSUE TITLE
Cannot play any channel [Windows]

### ISSUE THREAD

**Issue by GerhardK90** [4gray/iptvnator#39]
Thank you for maintaining this project. Unfortunately I am not able to play any channel (i tried two different playlists) - the screen just keeps loading. 

I also tried different players. The HTML Player gives me this Error:

![image](https://user-images.githubusercontent.com/3868214/116055892-79d42080-a67d-11eb-8cd7-e3240d35ff3f.png)

Thank you for your help!

**Comment by 4gray** [comment]
Thank you for the feedback! 
What version and OS are you using?

**Comment by GerhardK90** [comment]
Hey, 
sorry for the late reply i am on Windows 10 Pro Version 2004 OS Build 19041.867
Thank you!

**Comment by matthewxijp** [comment]
Hi, I have the same issue with no channel playing, I get a black screen which keeps loading.

Version: Windows 10 Home 2004 OS Build 19041.928

**Comment by 4gray** [comment]
What version of the application are you using?

**Comment by GerhardK90** [comment]
![image](https://user-images.githubusercontent.com/3868214/116818588-7bfe1980-ab6c-11eb-919b-93e9004dc733.png)

**Comment by 4gray** [comment]
Thanks @GerhardK90 !
Not sure what the problem is yet, I will try to check in more detail and maybe find a windows device :-)

**Comment by codevski** [comment]
This still a problem with 0.9?

**Comment by what-a** [comment]
I've been running it on Windows 10 and Linux for months. Works great!

**Comment by codevski** [comment]
getting constant loading on every channel on windows 10, account def works tried it on a linux box running hypnotix hrmm anyway to find debug logs on windows?

**Comment by what-a** [comment]
"account" sounds like you are trying to add an Xtream API playlist (using a user name and password). See #53

**Comment by codevski** [comment]
nah console logs show codec issue and html player doesnt show any errors or warnings in dev tools just infinite loading spin on any channels selected. At the moment don't have much time to delve into it more but when I get a chance again Ill create a separate issue since its not related the OP's error

**Comment by what-a** [comment]
As a test, try this public playlist. See if you can get anything to play from it:
https://iptv-org.github.io/iptv/index.m3u

**Comment by codevski** [comment]
Yeah it works fine, I think one channel had a codec issue but the html5 player worked off the bat. I have a feeling what ever format the provider is using isn't working with iptvnator
