### ISSUE TITLE
IPTVnator support h265 / HEVC

### ISSUE THREAD

**Issue by Yumega** [4gray/iptvnator#397]
make it  support  h265 / HEVC

**Comment by glennlunder** [comment]
I think a solution would be to use VLC / MPV as external player - they'll play anything, and then the built-in players aren't in use.

**Comment by 4gray** [comment]
yep, please use external players.

**Comment by alanmilinovic** [comment]
I don't like workaround with external player. In Jellyfin it works, I was able to play HVEC files normally after playlist in TV section. So it is possible.
