### ISSUE TITLE
Add File "Not supported"

### ISSUE THREAD

**Issue by starinspace** [4gray/iptvnator#40]
When I add "ADD VIA URL" it does work however, when I choose "ADD VIA FILE UPLOAD" with the same file but offline I get "File Was rejected, unsupported file format (test.m3u)". However, If I change the extension to *.m3u8 It does work. I hope you could fix this problem so the m3u-file can be used. :)

<img src="https://forumbilder.com/images/2021/04/27/Skarmklipp.png">

**Comment by 4gray** [comment]
Thank you for the bug report ;-)

I tried adding a playlist on Linux and on the MacOs, it worked in both cases. What operating system are you using? 
It would be interesting to know the mime type of your playlist. Currently, the following types are supported:

```
'application/x-mpegurl',
'application/octet-stream',
'application/mpegurl',
'application/vnd.apple.mpegurl',
'application/vnd.apple.mpegurl.audio',
'audio/x-mpegurl',
'audio/mpegurl'
```

**Comment by starinspace** [comment]
Oh, i forgott. I use Windows 10 64-bit. I have not checked if it might be utf-8 or similar if that might be a problem, but when adding a 8 in m3u it does load (m3u8).

I can send you a snippet of that file tomorrow.

**Comment by starinspace** [comment]
This does not work to open, however if I add a 8 to the extention m3u8 it does work.

saved as UTF-8 and file named test.m3u
`#EXTM3U

#EXTINF:-1 tvg-id="" tvg-name="Expressen TV" tvg-logo="https://i.imgur.com/Kt88QxS.png" group-title="SWEDEN",Expressen TV
https://httpcache0-03837-cachelive2.dna.qbrick.com/03837-cachelive2/smil:03837_tx2_720p/chunklist_b3628000.m3u8
`
