### ISSUE TITLE
Favorites not working in 0.16.0

### ISSUE THREAD

**Issue by Axel-Erfurt** [4gray/iptvnator#452]
**Describe the bug**
LMDE6 (Debian 12), iptvnator 0.16.0 Appimage
Switching playlist breaks favorites

**To Reproduce**
1. Open playlist, go to favorites, they are ok - see image 1
2. switch to another playlist, go to favorites, they are broken - _channel without name_ 
3. switch back  to previous playlist - same as 2. - see image 2

Global Favorites are ok.

![10_10_24_20_22_50](https://github.com/user-attachments/assets/cd797bc7-4b1c-44ef-8f94-feb5f333e2e0)
![10_10_24_20_23_53](https://github.com/user-attachments/assets/d8812988-b103-4f0c-9b28-38e3ef5334d3)

**Comment by 4gray** [comment]
Fixed in https://github.com/4gray/iptvnator/commit/b82fa5cc4a0634e54675294ae65ca379d49a9ebf and could be tested in v1.0.0-beta.3 - https://github.com/4gray/iptvnator/releases/tag/app-v1.0.0-3
