### ISSUE TITLE
Cant build on windows

### ISSUE THREAD

**Issue by Rrytel** [4gray/iptvnator#483]
**Describe the bug**
When trying to build on windows I get the error
Missing script: "electron:build:windows" 

**To Reproduce**
Clone repo and use 
npm run electron:build:windows

**Expected behavior**
It will build

**Screenshots**

**Desktop (please complete the following information):**
 - Electron application
 - OS: Windows
 - Browser chrome
 - Version 132.0.6834.15

**Comment by 4gray** [comment]
I updated the README. Since the project is moving to Tauri, you need to install Rust for building.
