### ISSUE TITLE
Multi channel EPG

### ISSUE THREAD

**Issue by MarisKay** [4gray/iptvnator#49]
While current EPG is good for a single channel. It is not how people would decide what to watch when having multiple channels available. That's why I would suggest not to invent something new but do it as all satellite boxes have done it before, like kodi simple iptv epg is doing and many others - multi channel EPG. You see your multiple channels, timeline, and what each channel has to offer. Here's a quick example i've found on the net: [https://www.sat-universe.com/imagehosting/2821884dc95a2ded497.png](url)

**Comment by nt74** [comment]
This is a function I've also been waiting for myself, like the Kodi [PVR IPTV Simple Client](https://github.com/kodi-pvr/pvr.iptvsimple) plugin

**Comment by 4gray** [comment]
First version of the feature is in included in v0.11.0, see: https://github.com/4gray/iptvnator/releases/tag/v0.11.0
