### ISSUE TITLE
v1.0.0-beta.3 mpv process is not killed when a new live channel is selected, or when mpv window is closed or exited

### ISSUE THREAD

**Issue by martymcflywa** [4gray/iptvnator#492]
**Describe the bug**
When using mpv as an external player, the mpv process remains open, even though a new channel is selected to play, or when the mpv window is closed or exited. The process remains open until quitting iptvnator. When switching channels, multiple instances of mpv will be opened, taking connections in the iptv provider account.

**To Reproduce**
1. Monitor processes with htop, filtering for "mpv"
2. Select mpv as external player in iptvnator settings
3. Start playing a live channel
4. Note the mpv process that has spawned
5. Play another channel
6. Note that the mpv process at step 4 remains open
7. Quit both mpv windows (cmd + q)
8. Note that both mpv processes remain open
9. Quit iptvnator
10. Note that the mpv processes exit

**Expected behavior**
I expect the mpv process to exit when i quit/close the window.
I expect the current mpv process to exit when i play another live channel.

**Screenshots**
No screenshots required.

**Desktop (please complete the following information):**
 - Tauri application
 - OS: MacOS Ventura
 - Version v1.0.0-beta.3

**Comment by what-a** [comment]
It would be nice to have the option to set mpv to auto close or stay open.  There are times when 2 sporting events are on at the same time and I would like the ability to launch them each from IPTVnator into mpv.

**Comment by martymcflywa** [comment]
This issue is solved by v1.0.0-beta4 since it also uses "--input-ipc-server", similar to v0.16.0. Thank you!

**Comment by bt4ibwem8** [comment]
for me it is broken even in beta4
