### ISSUE TITLE
Audio channel selection

### ISSUE THREAD

**Issue by MarisKay** [4gray/iptvnator#52]
Sometimes there are multiple audio channels available per stream (German/English for example). Would be great to be able to switch between different audio channels in this case. Currently i was not able to find this option for those channels.

**Comment by Axel-Erfurt** [comment]
It is already possible.
If there are several audio channels, a headphone symbol appears.

![iptvnator_audio](https://user-images.githubusercontent.com/2623542/119874992-8bcc0c00-bf26-11eb-90c5-805bdb60686e.png)

**Comment by 4gray** [comment]
As @Axel-Erfurt mentioned, this should work with the videojs-based player. Closing for now, if there are any issues then feel free to reopen.
