### ISSUE TITLE
URL Login (Xtream API)

### ISSUE THREAD

**Issue by hamzaalmali** [4gray/iptvnator#53]
Hello there,

Thank you for making this application. Health to your hands. How can I make login screen with URL, username and password to this app?

**Comment by 4gray** [comment]
Thank you for the feedback! 
Why do you need it, what is your use case?

**Comment by rainbow65** [comment]
It is a convenience to login to the application with dns, username and password. just wanted to make a suggestion

**Comment by what-a** [comment]
I have the same issue/question. How does one create a playlist that includes a user name and password? These work in VLC but don't seem to work in IPTVnator. An example of this type is:
http://iptvtree.net:8080/get.php?username=aumaleiptv&password=d051xyzaef399hp56&type=m3u

**Comment by 4gray** [comment]
@what-a The question is how to deal with these parameters (username, password, type), I suppose that they should  be passed as request body or maybe as part of the http header.

**Comment by what-a** [comment]
Wish I could offer a suggestion, but I'm clueless.

**Comment by analyserdmz** [comment]
I think the OP is asking how to have a login screen like IPTV Smarters does.

**Comment by what-a** [comment]
I now understand that this is know as an API / XtreamCode line. For example:
https://youtu.be/GJLEVWjh9EA

**Comment by iGerman00** [comment]
For the dev, found some docs https://xtream-ui.org/api-xtreamui-xtreamcode/

**Comment by bojangster** [comment]
+1 to this request. Your application will be the go-to option if you add this feature. If you can provide an update if you are planning to add this feature, it would be appreciated.

**Comment by kaypoush** [comment]
+1 this is a must-have feature

Some resources to help the devs:

https://github.com/linuxmint/hypnotix/blob/master/usr/lib/hypnotix/xtream.py

https://github.com/chazlarson/py-xtream-codes/blob/master/xtream.py

**Comment by 4gray** [comment]
@kaypoush thanks for sharing 👍 slowly started with the implementation

**Comment by 4gray** [comment]
Finally it's time to close this one, Xtream API is included in v0.14 🚀
