### ISSUE TITLE
Not loading channels

### ISSUE THREAD

**Issue by lucas-marx** [4gray/iptvnator#55]
Hi! first of all thank you for the app, It's the only one I've found that's simple and with a good interface. That's why I'm creating this issue:

I have a m3u list of channels that I've loaded on iptvnator, then it lists all the channels correctly but when I open it just goes on loading forever (tried on the VideoJs and html5 player). I've tried on three other players and it works fine and in no time. 

Does anyone how to solve/debug it? I'm on linux mint 20.1 and using the 0.7.0 v of the iptvnator

Thanks in advance!

**Comment by Axel-Erfurt** [comment]
Can you post a few lines from your m3u?

**Comment by lucas-marx** [comment]
It's paid, I think I can't

**Comment by Axel-Erfurt** [comment]
Does it look something like that?

```
#EXTM3U
#EXTINF:-1 tvg-name="Das Erste" group-title="ARD / ZDF" tvg-logo="http://logos.zattic.com/images/channels/logos/2a2a4aee64bbd6f7f817/white/84x48.png" tvg-id="",Das Erste
https://derste247livede.akamaized.net/hls/live/658317/daserste_de/master_640p_1028.m3u8
#EXTINF:-1 tvg-name="ZDF" group-title="ARD / ZDF" tvg-logo="http://logos.zattic.com/images/channels/logos/42a29350387ee5fda8fe/white/84x48.png" tvg-id="",ZDF
http://zdf-hls-15.akamaized.net/hls/live/2016498/de/low/master.m3u8
```

**Comment by lucas-marx** [comment]
yeah! just like that

**Comment by Axel-Erfurt** [comment]
And your http links are .m3u8 ?

**Comment by lucas-marx** [comment]
No, they all end with "/" and some numbers

**Comment by 4gray** [comment]
@lucas-marx could you please open the dev tools and check whether there are some errors visible?

**Comment by BliNDF123** [comment]
Hey, I was also having channels not loading, seems it can't play '.ts' format, had to change '&output=ts' to '&output=m3u8' on my providers URL to get m3u8 links.

**Comment by Woodyx** [comment]
> @lucas-marx could you please open the dev tools and check whether there are some errors visible?

@4gray Ich habe das gleiche Problem, wie kann man dir dabei in Hinsicht der Ausgabe von dev tools behilflich sein?
In der m3u haben die Links der Streams keine Endung.

**Comment by 4gray** [comment]
@Woodyx liegt vermutlich an der Playliste. Werden bei DevTools in der Console irgendwelche Fehler angezeigt? 
Nur so aus Interesse, probier mal bitte eine beliebige Playliste aus diesem Repository: https://github.com/jnk22/kodinerds-iptv (beliebige m3u-Datei aus dem `/iptv/clean`-Verzeichnis)
