### ISSUE TITLE
No video

### ISSUE THREAD

**Issue by johnfa155** [4gray/iptvnator#59]
Hi, I'm using this on Linux Mint 20.1 all seems to function correctly except there is no video displayed I've tried setting between Video JS and HTML5 but neither give anything

**Comment by Axel-Erfurt** [comment]
Which paylist do you use? Are all necessary codecs installed?

**Comment by johnfa155** [comment]
I use my m3u weblink and I have no idea about codecs all my other players work fine no problem

**Comment by TheMero-maker** [comment]
> Hi, I'm using this on Linux Mint 20.1 all seems to function correctly except there is no video displayed I've tried setting between Video JS and HTML5 but neither give anything

do you mean the player is waiting to load a stream ? could be a fault with your m3u list . i've tried the hypnotix one and hardly anything plays , buy my Pluto m3u runs perfectly

**Comment by johnfa155** [comment]
thanks but my m3u plays fine on all other iptv players and the epg loads fine it just doesn't show the video no fault messages at all it just doesn't work on my pc for me I'll stick with Astronica and Hypnotix instead I'd just like one that gives a good epg which hypnotix doesn't give at all even though its requested in the set up and the astronica one is pointless it only gives the channel I'm on

**Comment by TheMero-maker** [comment]
> thanks but my m3u plays fine on all other iptv players and the epg loads fine it just doesn't show the video no fault messages at all it just doesn't work on my pc for me I'll stick with Astronica and Hypnotix instead I'd just like one that gives a good epg which hypnotix doesn't give at all even though its requested in the set up and the astronica one is pointless it only gives the channel I'm on

Yeah hypnotix needs an epg badly , and astroncia is quite good but the GUI needs sorting badly . I'll stick to nator , it has the best functionality of all 3 so far , just be better if you could add more than one epg list

**Comment by johnfa155** [comment]
it certainly does, astronica is ok bur its epg is only for the channel your watching not much use for planning i'd be happy to use nator but it won't display anything the epg is fine just no video on any channel but the same m3u link works fine on all else so I don't know whats wrong

**Comment by johnfa155** [comment]
I still cant find anyway to get video to play, I'm using Linux mint 20.1 on a Lenovo X220 all other IPTV players are fine and work well on video

**Comment by TheMero-maker** [comment]
I still think it's something to do with the m3u file format  . I can get channels to play on hypnotix that refuse to play on iptvnator and vice versa

**Comment by johnfa155** [comment]
M3U format is fine it plays on every other player I have as well as my online ones no issues at all and having looked in my text viewer the formats the same as all my other m3u files which also don't play in this but work fine on every other player I have (8 in total) I just want one that plays and displays the epg in the same program, hynotix is great but no epg, same with vlc Astronica worked on epg once but the update it so often and it stops working correctly on epg Kodi is very good when it works but is very flaky and often just deosn't load at all.

**Comment by TheMero-maker** [comment]
Yeah astroncia is getting out of hand with updates . The only feature I think nator needs is to be able to view the EPG without having to switch through channels .. then it would be perfect

**Comment by johnfa155** [comment]
well for me seeing it would help, when the EPG works on astronia its ok but only the channel your viewing, the best by far is the Dreamlink box I have gives super video and full EPG but that's not on my pc one of them will get there one day

**Comment by TheMero-maker** [comment]
But I have noticed the EPG can be a bit sketchy on nator at times . Sometimes it shows a full days listings and others ya get only a few hours worth and it won't refresh until the next day . Astroncias can be way out time wise even if you adjust the timezone

**Comment by johnfa155** [comment]
I agree, none of them are as they should be, even get problems on my domestic Humax terrestrial box often hours at a time have 'No info' which is annoying if I want to set up reminders, but then if they all worked correctly there would be nothing to ever complain about

**Comment by TheMero-maker** [comment]
I had a Humax Freesat box a few years back , worst piece of junk ever . Constantly overheated and corrupting the hard drive so was always losing recordings . Bought a Manhattan box and it's been brilliant

**Comment by johnfa155** [comment]
my humax boxes have been fine I bought my FVP 4000 (terrestrial TV) on eBay replaced the faulty hard drive and its been perfect ever since I can set reminders which is great for me (the new sky Q boxes are rubbish you can only record things there's no way to set reminders).

**Comment by TheMero-maker** [comment]
We ditched sky ages ago . Between Freesat and IPTV there's more than enough rubbish to watch lol 😀

**Comment by johnfa155** [comment]
some of it is past rubbish, being old and retired now I find myself watching the old things like the fugitive and similar but I must say there are some things like Pluto that show a few good programs

**Comment by TheMero-maker** [comment]
Yeah I'm glued to the Dr who channel lol . Shame they took the bond channel off , but that's Amazon's fault me thinks

**Comment by johnfa155** [comment]
wasn't aware of those, I tend to stick to the internet ones like Pluto and the new plex tv is good

**Comment by TheMero-maker** [comment]
Ah are you watching the UK version , I've got the American one . Don't wanna post a link cause we're way off topic as it is lol , how do ya send a Pvt msg in this thing

**Comment by johnfa155** [comment]
Not sure I'll check tomorrow as I'm off to eat and watch tv npw
--
John
     Tuesday, 15 June 2021, 04:38pm +01:00 from mick  ***@***.*** :

**Comment by 4gray** [comment]
Duplicate, see #65
