### ISSUE TITLE
No channels supported?

### ISSUE THREAD

**Issue by awik32** [4gray/iptvnator#60]
Hi all,

I've installed IPTVnator on Linux Mint 19.3 (Tricia) using snap, and I'm finding that no channels are working.  I get "The media could not be loaded ..." error.

-Albert.

**Comment by Axel-Erfurt** [comment]
What does your playlist look like?

Show some lines.

**Comment by 4gray** [comment]
More info needed. Feel free to reopen if the problem still exists.
