### ISSUE TITLE
Can't play streams when in 'output=ts' links?

### ISSUE THREAD

**Issue by BliNDF123** [4gray/iptvnator#63]
I downloaded IPTVNator and was not getting any channels loading, came here and saw other users were having the same issue.  As I mentioned in another post I tried changing the output type on my link from 'output=ts' which doesn't work at all it seems, to 'output=m3u8' that works for the most part, but sometimes some channels will just have audio, when that happens I seem to create a new bug sometimes have have a channel start coming up over and over on other channels I switch to.  For the no video issue, are there codecs I need to have installed?

**Comment by Axel-Erfurt** [comment]
Yes, sometimes there is a problem when additional additions are appended after m3u8.

for example, I had 

https://rbblive-lh.akamaihd.net/i/rbb_brandenburg@349369/index_3_av-p.m3u8?sd=4&set-segment-duration=responsive&rebase=on

I shortened it

https://rbblive-lh.akamaihd.net/i/rbb_brandenburg@349369/index_3_av-p.m3u8

and it loads.

**Comment by BliNDF123** [comment]
> Yes, sometimes there is a problem when additional additions are appended after m3u8.
> 
> for example, I had
> 
> https://rbblive-lh.akamaihd.net/i/rbb_brandenburg@349369/index_3_av-p.m3u8?sd=4&set-segment-duration=responsive&rebase=on
> 
> I shortened it
> 
> https://rbblive-lh.akamaihd.net/i/rbb_brandenburg@349369/index_3_av-p.m3u8
> 
> and it loads.

Hmmm, this is different.  I see what you're saying, but I mean if it's not .m3u8, it's .ts instead, then it doesn't work.  And even some .m3u8 will sometimes only give me audio.

**Comment by 4gray** [comment]
@BliNDF123 Since the player is based on the hls.js library, could you check please if one of the streams from your playlist works on the hls demo page - https://hls-js.netlify.app/demo/

**Comment by BliNDF123** [comment]
> @BliNDF123 Since the player is based on hls.js library, could you check please if one of the streams from your playlist works on the hls demo page - https://hls-js.netlify.app/demo/

Doesn't work if the link ends with a .ts for an extension, only .m3u8

**Comment by what-a** [comment]
@4gray It's becoming apparent to me that hls.js doesn't have the same ability to play a variety of IPTV streams types compared to VLC or MPV. Ultimately, I fear this limitation will inhibit the adoption of IPTVnator by users, and lead to more issues being reported here. So, I'm wondering...  How difficult would it be to for IPTVnator to shift from hls.js to MPV? I love the GUI and features of IPTVnator and would love to see it paired with the playback versatility of MPV.
https://mpv.io/
https://github.com/mpv-player/mpv

**Comment by 4gray** [comment]
@what-a Thanks for the links. If I understand correctly, mpv is a separate player/application, not a library. So I don't see how this project can be integrated in iptvnator/electron app. The only thing I can imagine is a function which when clicking on a channel will ask which player to open (like open with on Android), but I'm not sure how necessary and possible this is.

**Comment by X0022000** [comment]
Request Head
Hi , please can u help me tô make my Channel link
I got that
Request head
http://199.27.60.240:2030/streams/340_.m3u8
GET /streams/340_.m3u8 HTTP/1.1
X-IPTV-TOKEN: V9KEnCH-nM7ZvmbIP-4ZLkfLtalWt1uIX1fYkx-dUuURNQAWMrOVU3ytBAQewwcuDH_2bBJFPZ0aSBSYvRQvUtbY9nleddMN3ocI
User-Agent: 44644hs556622djakdahdhad
Accept-Encoding: gzip
Host: 199.127.60.230:2030
Connection: Keep-Alive

Response Head

HTTP/1.1 200 OK
Server: nginx
Date: Mon, 25 Apr 2022 03:30:30 GMT
Content-Type: application/vnd.apple.mpegurl
Content-Length: 279
Connection: keep-alive
Last-Modified: Mon, 25 Apr 2022 03:30:22 GMT
ETag: "626615ce-117"
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, OPTIONS
Access-Control-Allow-Headers: DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range
Accept-Ranges: bytes

**Comment by Vinay-Ban** [comment]
hi. I have Iptvnator 0.13.0.exe installed in my laptop, but I'm unable to play m3u8 file through Iptvnator. neither playlist nor m3u8 text are being played. but same m3u8 file is playing in vlc media player, so I know there is not any issue in my playlist. how to fix it?

**Comment by Vinay-Ban** [comment]
files which are being played in vlc, are not playing in Iptvnator, and the files which are being played in Iptvnator, are not playing in vlc. both m3u and m3u8.

**Comment by 4gray** [comment]
Hopefully the integration of mpv and vlc player should solve these issues.
