### ISSUE TITLE
No display

### ISSUE THREAD

**Issue by ghost** [4gray/iptvnator#65]
I'm using a Lenovo X220 running Linux Mint 20.1 my IPTV loads into your program as I see the channel logo's but won't display any video it works fine with every other player I have I'm just looking for one that actually give EPG

**Comment by Axel-Erfurt** [comment]
Show some lines of your playlist.

**Comment by johnfa155** [comment]
sorry this doesn't make sense, what play list?  I'm using my standard M3U file that works fine on all other players, like Astronica,hypnotix and VLC its just this iptvnator that doesn't show any video but somethings loading as all the channels show with logo's fine

**Comment by Axel-Erfurt** [comment]
Astronica,hypnotix are using mpv, iptvnator uses videojs or html5  and works fine on my Mint 20.1.

You may be missing some codecs.

**Comment by Axel-Erfurt** [comment]
In iptvnator use **Open DevTools** from the help menu or start iptvnator from terminal to see messages.

**Comment by johnfa155** [comment]
right, thanks that gave me the following so what now?
vendor.js:83276 Angular is running in development mode. Call enableProdMode() to enable production mode.
DevTools failed to load SourceMap: Could not load content for file:///snap/iptvnator/14/resources/app.asar/dist/runtime.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/iptvnator/14/resources/app.asar/dist/polyfills.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/iptvnator/14/resources/app.asar/dist/styles.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/iptvnator/14/resources/app.asar/dist/vendor.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/iptvnator/14/resources/app.asar/dist/main.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/iptvnator/14/resources/app.asar/dist/home-home-module.js.map:

**Comment by 4gray** [comment]
@johnfa155 it looks fine, nothing critical. Could you please try that: https://github.com/4gray/iptvnator/issues/63#issuecomment-866656378

**Comment by hiraaaad** [comment]
Hi 4gray, 

I tried a m3u8 playlist in Iptvnator on mac, but it returns only audio but no video. 

The link works fine on VLC. I also tried the hls demo page and it returned the following errors: 

````
Status:
377.711 | Media element detached
377.712 | Loading **LINK**/index.m3u8
377.715 | Loading manifest and attaching video element...
377.743 | Media element attached`

Error:
Cannot load LINK/index.m3u8HTTP response code:0 This might be a CORS issue, consider installing Allow-Control-Allow-Origin Chrome Extension
378.736 | A network error occurred: manifestLoadError
````
I also checked other links from my providers that they work fine in Iptvnator but the demo page still can't stream it. 

Would you please help me out and please let me know what other information you may require to resolve this problem. 

I can hear the audio but for video on mac is black screen only.

Thanks for your time.
