### ISSUE TITLE
I have done something to help it become localized in Chinese.

### ISSUE THREAD

**Issue by JoJenH** [4gray/iptvnator#67]
I have done something to help it become localized in Chinese. But I am new in TypeScript. I don’t know how to modify your code. 
我做了一些可以帮助您汉化iptynator的工作。但是我在TypeScript方面是个完全的新手。我不知道怎样在您的代码上完成修改。
So I put the [zh.json](https://github.com/JoJenH/iptvnator_zh) in my GitHub repository. 
所以我把我写的zh.json放在了我自己的GitHub仓库中。
Hope it is useful to you.
希望它可以帮的到你。
Thank you for your contribution to iptynator! 
感谢您对iptvnator的贡献！
There is the link of [zh.json](https://github.com/JoJenH/iptvnator_zh)  https://github.com/JoJenH/iptvnator_zh.

**Comment by 4gray** [comment]
Thank you very much for the translation, it's integrated now :cn: (https://github.com/4gray/iptvnator/commit/a497f0570175618d7053b53fd47aa907e6361f17)
