### ISSUE TITLE
WordPress or Blogger.com embed page ? m3u v. m3u8. Youtube support.

### ISSUE THREAD

**Issue by siliconhippy** [4gray/iptvnator#69]
Hi 4gray,

Looks like great work.

1. Can this be embedded in a wordpress.org or blogger.com page ?

Noob here, but it is frustrating to see that big names like JWP (expensive + BW charges + no Youtube support) and other WP $plugins don't seem to play my m3u/8 playlist URL, or this kind of public IPTV one (both play fine in VLC or smartIPTV chrome extension):

https://iptv-org.github.io/iptv/countries/ca.m3u

(doesn't play in https://hls-js.netlify.app/demo/ or https://developer-tools.jwplayer.com/stream-tester/ )

2. Is this an m3u to m3u8 conversion issue you say you support ? (Should be simple.)

3. Does your player support youtube https URLs, or some m3u/8 conversion (e.g., streamlink/liveproxy or VLC conversion of youtube http URL Network Stream  input to Codec Info link (bottom box) saved to a m3u playlist ?)

Cheers,
Shippy.

**Comment by Axel-Erfurt** [comment]
https://iptv-org.github.io/iptv/countries/ca.m3u works fine in  iptvnator.

**Comment by siliconhippy** [comment]
Axel,

Thanks, I thought so !

How about #1 above?
Is VLC.js now available, which supposedly is needed for WordPress type plugins which now all seem to use hls.js that supports m3u8 only ?

Cheers, 😸
Shippy.

**Comment by 4gray** [comment]
Hi @siliconhippy, thanky you for the feedback!
Regarding 1. unfortunately, this is not possible.
