### ISSUE TITLE
Referrer/Origin-locked streams won't work

### ISSUE THREAD

**Issue by LaneSh4d0w** [4gray/iptvnator#74]
Due to some factors, some links might be locked using where they came from (referrer and/or origin). Some links, because of that, can be falsely given a 403 when trying to load them.

**Comment by 4gray** [comment]
How are user-agent and referer defined in the link? At the moment iptvnator supports two formats, see https://github.com/4gray/iptvnator/issues/57

**Comment by LaneSh4d0w** [comment]
> How are user-agent and referer defined in the link? At the moment iptvnator supports two formats, see https://github.com/4gray/iptvnator/issues/57 

Defined as external VLC-specific options.

#EXTVLCOPT:http-referrer=https://ssh101.com/ as an example.

Maybe you can translate this to make it work in the Kodi way.

If you need some things :

http-user-agent = User-Agent
http-referrer = Referer
Origin however isn't supported in VLC (or I haven't found yet.

**Comment by 4gray** [comment]
Took a random stream from ssh101, in this way it works fine for me: 
`#EXTM3U
#EXTINF:-1 tvg-name="test" tvg-id="test",Test
#EXTVLCOPT:http-referrer=https://ssh101.com/
#EXTVLCOPT:http-user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5)
https://tna5.bozztv.com/crotvhd/index.m3u8`

**Comment by rossbeck** [comment]
Was it ever implemented to let us add custom referers to playlists? I can see where it will let me enter a User agent but can't find the referer section. Is the solution to import a file with it already integrated rather than just adding a playlist via URL and providing the details later? Thanks
