### ISSUE TITLE
Support mp4 for movies?

### ISSUE THREAD

**Issue by izoodeh** [4gray/iptvnator#76]
the media could not be loaded either because the server or network failed or because the format is not supported.

**Comment by izoodeh** [comment]
the vod system doesn't work in the app because the html player is in an infinite load and the js player doesn't support vod.

how do i add support for vod, movies and tv show?

https://i.imgur.com/wsSe239.png

**Comment by analyserdmz** [comment]
That would be interesting. Voting for it..
