### ISSUE TITLE
Free2View TV - multiple playlist / EPG sources?

### ISSUE THREAD

**Issue by geonsey** [4gray/iptvnator#79]
Good morning. A member of my Free2View TV Discord referred us to this app... I haven't had a chance to check it out yet, but I am endorsing Perfect Player because it allows for multiple playlist and xml EPG sources. Does yours? If so, this could be the new official player for Free2View TV! -Georges.
PS: Stupid question (kinda techno dumb, so forgive me), but does this come as pre-built apps for windows and Android apk? (Yeah you can all laugh at me if this is supposed to be obvious lmao)

**Comment by what-a** [comment]
Yes, IPTVnator accomidates multiple playlists and xml EPG sources.  I am running IPTVnator on multiple laptops under Windows and Linux without any problem. I don't have a smart phone so I can't speak to that.

**Comment by geonsey** [comment]
Well, I will eventually (but not for a long time) discontinue using github for the repo of my Free2View TV playlists. I have better control over the lists and the content using OpenDrive. As for iptv-org, though I respect this repo, there are a LOT of questionable sources there, so I still prefer somehow vetting the URL's for my project. That being said, if you find some unique links in F2V which you want to add to your own repo, feel free, nothing I use are bootlegs and I have vetted them as official network streams.

As for IPTVnator... is there an official android app (or apk) that can be installed on Android TV players?

**Comment by what-a** [comment]
No, there isn't an official android app for IPTVnator.

Re: multiple EPG sources. Currently, IPTVnator allows for one EPG only.  Would it be better to allow a unique EPG for each playlist (i.e. an EPG can be user defined as part of each playlist setup)?

**Comment by 4gray** [comment]
@what-a Thanks for the answer, it's exactly as you wrote. In the future, I can imagine the possibility of adding several EPG sources at once. 
Closing the issue for now, if you have any questions feel free to reopen.
