### ISSUE TITLE
Suggestion: Move the "Upload or select other playlist" icon.

### ISSUE THREAD

**Issue by what-a** [4gray/iptvnator#83]
**Issue:** Currently one has access to the "Upload or select other playlist" icon when viewing "ALL CHANNELS." However, it cannot be seen if one is viewing "GROUPS" or "FAVORITES."  

**Suggestion:** Move the "Upload or select other playlist" icon upward so it maintains visibility and access regardless of viewing "ALL CHANNELS", "GROUPS" or "FAVORITES."

![image](https://user-images.githubusercontent.com/88639906/135652306-750bf6d9-c916-4a0d-926d-2df5e31c8836.png)

**Comment by 4gray** [comment]
Finally reworked the channel list header a bit.
![SCR-20220219-x7h](https://user-images.githubusercontent.com/1503032/154821882-3819503c-18ab-4270-bcf1-7fa4c639a227.png)
