### ISSUE TITLE
Feature request: VLC player

### ISSUE THREAD

**Issue by fragarray** [4gray/iptvnator#90]
https://wiki.videolan.org/Documentation:WebPlugin/

it looks like something that can be fit into this project.

**Comment by jmros** [comment]
+1

**Comment by spotanjo3** [comment]
+1

**Comment by what-a** [comment]
VLC and mpv are both far more capable at handling less than perfect IPTV streams than hls.js (which IPTVnator currently utilizes).  Yes, both VLC and mpv are excellent players, however when testing VLC vs. mpv I'm finding mpv to be the lighter and faster of the two. I'm hoping 4gray will consider migrating IPTVnator from hls.js to mpv.
I'm not a coder so I can't help, but I would certainly donate to such an effort.
https://mpv.io/
https://github.com/mpv-player/mpv

**Comment by ql3d** [comment]
i cant get any streams to play , everything else loads fine though,, maybe bc its hls

**Comment by jezokshe** [comment]
Exo Player The BEst

**Comment by ovived** [comment]
> Exo Player The BEst

ExoPlayer is only for android, if this is running on a webapp or windows/desktop app you cant use exoplayer.

**Comment by 4gray** [comment]
VLC integration is available in v0.15
