### ISSUE TITLE
Player just loading and saying "The media could not be loaded, either because the server or network failed or because the format is not supported."

### ISSUE THREAD

**Issue by isak102** [4gray/iptvnator#94]
I am trying to play a M3U url playlist and I get this message when I try to play the stream. There is no error with the m3u playlist because it is working on other media players. 
![2021-10-17_18-55](https://user-images.githubusercontent.com/90389894/137637223-c6ebcf5b-5322-4191-8c9e-d99b26d9a23f.png)

**Comment by what-a** [comment]
Can you post a few lines from your m3u playlist for us to test?

**Comment by isak102** [comment]
> Could you post a few lines from your m3u playlist for testing?

I managed to fix this specific problem by changing the ending of the playlist from "output=ts" to "output=m3u8", now all channels load properly but some don't play sound. Do you have any idea on how to fix this?

**Comment by 4gray** [comment]
Please make sure that the playlist is valid and it works

**Comment by Shazgul** [comment]
Got the Same Error when i try it via. Stalker Portal MACs.
