### ISSUE TITLE
Feature Request: Universal Favorites Channel Filter/Playlist

### ISSUE THREAD

**Issue by timcarrutherz** [4gray/iptvnator#97]
You are currently able to create a favorite channel playlist per m3u playlist and can only access them when you visit each individual m3u playlist. Is it possible to implement a universal favorite playlist, so all of you favorited channels are in one place, without needing jump between m3u playlists all the time?

**Comment by 4gray** [comment]
Thanks for the suggestion! I like the idea, added to the roadmap :rocket:

**Comment by 4gray** [comment]
Added a global playlist to the PWA version, anyone interested can test it there - https://iptvnator.vercel.app/
