### ISSUE TITLE
Feature Request: improvements in working with epg+m3u

### ISSUE THREAD

**Issue by java3000** [4gray/iptvnator#98]
Thank you for the excellent IPTV  program!

And it can become even better if it can take more data from m3u files
because many of m3u-s have tags with the channel name like this "tvg-id"

`#EXTINF:-1 tvg-id="3ABN.us" tvg-country="US" tvg-language="English" tvg-logo="https://i.imgur.com/GVZuKc7.png" group-title="Religious",3ABN (720p) [Not 24/7]`

which can link them to the epg files where you can also find a link to the channel like "channel" attribute in code below

`<programme start="20211211000000 +0000" stop="20211211003000 +0000" channel="3ABN.us"><title lang="en">Jesus 4 Asia Now</title><category lang="en">Religious</category></programme>`

Which allows you to match channels with the program.
Also allows you to use the best program for the playlist.
And more of that, dynamically load EPG from m3u files by links like

`#EXTM3U url-tvg="https://iptv-org.github.io/epg/guides/us/tvtv.us.epg.xml"`

in start of m3u file.

**Comment by phartshorn** [comment]
I've just created an MR that uses the tvg-id from the playlist to match the epg entry.

https://github.com/4gray/iptvnator/pull/106

**Comment by 4gray** [comment]
#106 is merged, thank you guys! 🚀
